// web-next/src/components/app/dialogs/create-scene-dialog.tsx
import { useState } from 'react'
import { Button } from '@/components/ui/button'
import {
    Dialog,
    DialogContent,
    DialogFooter,
    DialogHeader,
    DialogTitle,
} from '@/components/ui/dialog'
import { Input } from '@/components/ui/input'

interface CreateSceneDialogProps {
    open: boolean
    onOpenChange: (open: boolean) => void
    onCreate: (name: string) => void
}

export function CreateSceneDialog({ open, onOpenChange, onCreate }: CreateSceneDialogProps) {
    const [name, setName] = useState('')

    function handleSubmit(e: React.FormEvent) {
        e.preventDefault()
        if (!name.trim()) return
        onCreate(name.trim())
        setName('')
        onOpenChange(false)
    }

    return (
        <Dialog open={open} onOpenChange={onOpenChange}>
            <DialogContent>
                <DialogHeader>
                    <DialogTitle>새 씬</DialogTitle>
                </DialogHeader>
                <form onSubmit={handleSubmit} className="flex flex-col gap-4">
                    <Input
                        value={name}
                        onChange={(e) => setName(e.target.value)}
                        placeholder="씬 이름..."
                        autoFocus
                    />
                    <DialogFooter>
                        <Button type="button" variant="outline" onClick={() => onOpenChange(false)}>
                            취소
                        </Button>
                        <Button type="submit" disabled={!name.trim()}>
                            만들기
                        </Button>
                    </DialogFooter>
                </form>
            </DialogContent>
        </Dialog>
    )
}

// web/src/lib/components/app/dialogs/create-scene-dialog.svelte
<script lang="ts">
    import * as Dialog from '$lib/components/ui/dialog'
    import { Input } from '$lib/components/ui/input'
    import { Button } from '$lib/components/ui/button'
    import { Label } from '$lib/components/ui/label'

    let {
        open = $bindable(false),
        oncreate,
    }: {
        open?: boolean
        oncreate: (name: string) => void
    } = $props()

    let name = $state('')

    function handleSubmit() {
        if (!name.trim()) return
        oncreate(name.trim())
        name = ''
        open = false
    }
</script>

<Dialog.Root bind:open>
    <Dialog.Content class="sm:max-w-sm">
        <Dialog.Header>
            <Dialog.Title>새 씬 만들기</Dialog.Title>
        </Dialog.Header>
        <form
            onsubmit={(e) => {
                e.preventDefault()
                handleSubmit()
            }}
        >
            <div class="flex flex-col gap-4 py-2">
                <div class="flex flex-col gap-1.5">
                    <Label for="scene-name">씬 이름</Label>
                    <Input id="scene-name" bind:value={name} placeholder="씬 이름 입력..." autofocus />
                </div>
            </div>
            <Dialog.Footer>
                <Button variant="outline" type="button" onclick={() => (open = false)}>취소</Button>
                <Button type="submit" disabled={!name.trim()}>만들기</Button>
            </Dialog.Footer>
        </form>
    </Dialog.Content>
</Dialog.Root>
