// web/src/features/scene/variation-editor.tsx
import {
    closestCenter,
    DndContext,
    type DragEndEvent,
    PointerSensor,
    useSensor,
    useSensors,
} from '@dnd-kit/core'
import {
    arrayMove,
    SortableContext,
    useSortable,
    verticalListSortingStrategy,
} from '@dnd-kit/sortable'
import { CSS } from '@dnd-kit/utilities'
import type { PromptVariable, VariationDraft } from '@nai-factory/shared'
import { GripVertical, Plus, Trash2, X } from 'lucide-react'

import { CodeEditor } from '@/components/code-editor/code-editor'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { tempId } from '@/lib/optimistic'
import { variableValidationMessage } from '@/lib/prompt-variables'

interface VariationEditorProps {
    variations: VariationDraft[]
    onChange: (variations: VariationDraft[]) => void
}

type SortableVariationProps = {
    id: string | number
    variation: VariationDraft
    varIdx: number
    onAddKey: (varIdx: number) => void
    onRemoveVariation: (varIdx: number) => void
    onRemoveKey: (varIdx: number, keyIdx: number) => void
    onUpdateKey: (varIdx: number, keyIdx: number, newKey: string) => void
    onUpdateValue: (varIdx: number, keyIdx: number, value: string) => void
}

function itemId(variation: VariationDraft, index: number) {
    return variation.id ?? `new-${index}`
}

function SortableVariation({
    id,
    variation,
    varIdx,
    onAddKey,
    onRemoveVariation,
    onRemoveKey,
    onUpdateKey,
    onUpdateValue,
}: SortableVariationProps) {
    const { attributes, listeners, setNodeRef, transform, transition, isDragging } = useSortable({
        id,
    })

    const style = {
        transform: CSS.Transform.toString(transform),
        transition,
    }
    const validationMessage = variableValidationMessage(variation.variables)

    return (
        <div
            ref={setNodeRef}
            style={style}
            className={`flex gap-2 ${isDragging ? 'opacity-50' : ''}`}
        >
            <button
                type="button"
                {...attributes}
                {...listeners}
                className="mt-3 flex h-10 w-10 shrink-0 cursor-grab items-center justify-center rounded-md border bg-background text-muted-foreground active:cursor-grabbing"
            >
                <GripVertical className="h-4 w-4" />
            </button>

            <div className="min-w-0 flex-1 rounded-md border bg-card p-3">
                <div className="mb-3 flex items-center justify-between gap-2">
                    <span className="min-w-0 text-xs font-medium text-muted-foreground">
                        변수 세트 {varIdx + 1}
                    </span>
                    <div className="flex shrink-0 items-center gap-1">
                        <Button
                            variant="ghost"
                            size="icon-sm"
                            className="text-muted-foreground"
                            onClick={() => onAddKey(varIdx)}
                        >
                            <Plus className="h-3.5 w-3.5" />
                        </Button>
                        <Button
                            variant="ghost"
                            size="icon-sm"
                            className="text-muted-foreground hover:text-destructive"
                            onClick={() => onRemoveVariation(varIdx)}
                        >
                            <Trash2 className="h-3.5 w-3.5" />
                        </Button>
                    </div>
                </div>

                <div className="rounded-md border bg-background p-3">
                    <div className="flex flex-col gap-2">
                        {variation.variables.map(({ key, value }, keyIdx) => (
                            <div
                                // Index keys: draft rows can share empty keys until edited.
                                key={keyIdx}
                                className="flex flex-col gap-1"
                            >
                                <div className="flex items-center gap-1.5">
                                    <Input
                                        className="flex-1 px-2 font-mono"
                                        value={key}
                                        placeholder="변수명"
                                        onChange={(e) =>
                                            onUpdateKey(varIdx, keyIdx, e.target.value)
                                        }
                                    />
                                    <Button
                                        variant="ghost"
                                        size="icon-xs"
                                        className="shrink-0 text-muted-foreground"
                                        onClick={() => onRemoveKey(varIdx, keyIdx)}
                                    >
                                        <X className="h-3 w-3" />
                                    </Button>
                                </div>
                                <CodeEditor
                                    value={value}
                                    placeholder="값 (태그, 프롬프트 등)..."
                                    minLines={2}
                                    onChange={(v) => onUpdateValue(varIdx, keyIdx, v)}
                                />
                            </div>
                        ))}
                        {validationMessage && (
                            <p className="text-[11px] text-destructive">{validationMessage}</p>
                        )}
                    </div>
                </div>
            </div>
        </div>
    )
}

export function VariationEditor({ variations, onChange }: VariationEditorProps) {
    const sensors = useSensors(useSensor(PointerSensor, { activationConstraint: { distance: 8 } }))
    const ids = variations.map(itemId)

    function addVariation() {
        onChange([...variations, { id: tempId(), variables: [] }])
    }

    function removeVariation(i: number) {
        onChange(variations.filter((_, idx) => idx !== i))
    }

    function addKey(varIdx: number) {
        const updated = [...variations]
        updated[varIdx] = {
            ...updated[varIdx],
            variables: [...updated[varIdx].variables, { key: '', value: '' }],
        }
        onChange(updated)
    }

    function removeKey(varIdx: number, keyIdx: number) {
        const updated = [...variations]
        updated[varIdx] = {
            ...updated[varIdx],
            variables: updated[varIdx].variables.filter((_, index) => index !== keyIdx),
        }
        onChange(updated)
    }

    function updateKey(varIdx: number, keyIdx: number, newKey: string) {
        const updated = [...variations]
        const variables: PromptVariable = updated[varIdx].variables.map((variable, index) =>
            index === keyIdx ? { ...variable, key: newKey } : variable,
        )
        updated[varIdx] = { ...updated[varIdx], variables }
        onChange(updated)
    }

    function updateValue(varIdx: number, keyIdx: number, value: string) {
        const updated = [...variations]
        updated[varIdx] = {
            ...updated[varIdx],
            variables: updated[varIdx].variables.map((variable, index) =>
                index === keyIdx ? { ...variable, value } : variable,
            ),
        }
        onChange(updated)
    }

    function handleDragEnd(event: DragEndEvent) {
        const { active, over } = event
        if (!over || active.id === over.id) return

        const oldIndex = ids.indexOf(active.id)
        const newIndex = ids.indexOf(over.id)
        if (oldIndex < 0 || newIndex < 0) return

        onChange(arrayMove(variations, oldIndex, newIndex))
    }

    return (
        <div className="flex flex-col gap-3">
            <DndContext
                sensors={sensors}
                collisionDetection={closestCenter}
                onDragEnd={handleDragEnd}
            >
                <SortableContext items={ids} strategy={verticalListSortingStrategy}>
                    <div className="flex flex-col gap-3">
                        {variations.map((variation, varIdx) => (
                            <SortableVariation
                                key={itemId(variation, varIdx)}
                                id={itemId(variation, varIdx)}
                                variation={variation}
                                varIdx={varIdx}
                                onAddKey={addKey}
                                onRemoveVariation={removeVariation}
                                onRemoveKey={removeKey}
                                onUpdateKey={updateKey}
                                onUpdateValue={updateValue}
                            />
                        ))}
                    </div>
                </SortableContext>
            </DndContext>

            <Button
                variant="outline"
                size="sm"
                className="gap-1.5 self-start"
                onClick={addVariation}
            >
                <Plus className="h-3.5 w-3.5" />
                변수 세트 추가
            </Button>
        </div>
    )
}

// web/src/lib/components/app/project/variation-editor.svelte
<script lang="ts">
    import { Input } from '$lib/components/ui/input'
    import { Button } from '$lib/components/ui/button'
    import { CodeEditor } from '$lib/components/ui/code-editor'
    import PlusIcon from '@lucide/svelte/icons/plus'
    import TrashIcon from '@lucide/svelte/icons/trash-2'
    import XIcon from '@lucide/svelte/icons/x'

    type Variation = Record<string, string>

    let {
        variations = $bindable([]),
        onchange,
        layout = 'col',
    }: {
        variations?: Variation[]
        onchange?: (v: Variation[]) => void
        layout?: 'col' | 'row'
    } = $props()

    function addVariation() {
        variations = [...variations, {}]
        onchange?.(variations)
    }

    function removeVariation(i: number) {
        variations = variations.filter((_, idx) => idx !== i)
        onchange?.(variations)
    }

    function addKey(varIdx: number) {
        const updated = [...variations]
        updated[varIdx] = { ...updated[varIdx], '': '' }
        variations = updated
        onchange?.(variations)
    }

    function removeKey(varIdx: number, key: string) {
        const updated = [...variations]
        const { [key]: _, ...rest } = updated[varIdx]
        updated[varIdx] = rest
        variations = updated
        onchange?.(variations)
    }

    function updateKey(varIdx: number, oldKey: string, newKey: string) {
        const updated = [...variations]
        const obj = { ...updated[varIdx] }
        const value = obj[oldKey] ?? ''
        delete obj[oldKey]
        obj[newKey] = value
        updated[varIdx] = obj
        variations = updated
        onchange?.(variations)
    }

    function updateValue(varIdx: number, key: string, value: string) {
        const updated = [...variations]
        updated[varIdx] = { ...updated[varIdx], [key]: value }
        variations = updated
        onchange?.(variations)
    }
</script>

<div class="flex flex-col gap-3">
    <div class={layout === 'row' ? 'flex flex-nowrap gap-4' : 'flex flex-col gap-3'}>
        {#each variations as variation, varIdx (varIdx)}
        <div class="rounded-md border bg-card p-3 {layout === 'row' ? 'w-96 shrink-0' : ''}">
            <div class="mb-2 flex items-center justify-between">
                <span class="text-xs font-medium text-muted-foreground">변수 세트 {varIdx + 1}</span>
                <Button
                    variant="ghost"
                    size="icon"
                    class="h-6 w-6 text-muted-foreground hover:text-destructive"
                    onclick={() => removeVariation(varIdx)}
                >
                    <TrashIcon class="h-3.5 w-3.5" />
                </Button>
            </div>

            <div class="flex flex-col gap-2">
                {#each Object.entries(variation) as [key, value], keyIdx (keyIdx)}
                    <div class="flex flex-col gap-1">
                        <!-- Key row -->
                        <div class="flex items-center gap-1.5">
                            <Input
                                class="h-7 flex-1 px-2 font-mono text-xs"
                                value={key}
                                placeholder="변수명"
                                onblur={(e) =>
                                    updateKey(varIdx, key, (e.target as HTMLInputElement).value)}
                                onkeydown={(e) => {
                                    if (e.key === 'Enter')
                                        updateKey(varIdx, key, (e.target as HTMLInputElement).value)
                                }}
                            />
                            <Button
                                variant="ghost"
                                size="icon"
                                class="h-6 w-6 shrink-0 text-muted-foreground"
                                onclick={() => removeKey(varIdx, key)}
                            >
                                <XIcon class="h-3 w-3" />
                            </Button>
                        </div>
                        <!-- Value editor -->
                        <CodeEditor
                            value={value}
                            placeholder="값 (태그, 프롬프트 등)..."
                            minLines={layout === 'row' ? 4 : 2}
                            onchange={(v) => updateValue(varIdx, key, v)}
                        />
                    </div>
                {/each}
            </div>

            <Button
                variant="ghost"
                size="sm"
                class="mt-2 h-6 w-full gap-1 text-xs text-muted-foreground"
                onclick={() => addKey(varIdx)}
            >
                <PlusIcon class="h-3 w-3" />
                변수 추가
            </Button>
        </div>
    {/each}
    </div>

    <Button variant="outline" size="sm" class="gap-1.5" onclick={addVariation}>
        <PlusIcon class="h-3.5 w-3.5" />
        변수 세트 추가
    </Button>
</div>
