// web-next/src/components/app/sidebar/sidebar-prompt/index.tsx
import { useQuery, useQueryClient } from '@tanstack/react-query'
import { AlignLeft } from 'lucide-react'
import { useEffect, useRef, useState } from 'react'
import { SidebarHeader } from '@/components/ui/sidebar'
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs'
import { api } from '@/lib/api'
import { qk } from '@/lib/queries'
import { debounce } from '@/lib/utils'
import { CharacterPromptEditor } from './character-prompt-editor'
import { PromptEditor } from './prompt-editor'
import { PromptVariableEditor } from './prompt-variable-editor'
import { VibeTransferEditor } from './vibe-transfer-editor'

type SidebarPromptProps = {
    projectId: number
}

export function SidebarPrompt({ projectId }: SidebarPromptProps) {
    const queryClient = useQueryClient()

    const projectQuery = useQuery({
        queryKey: qk.project(projectId),
        queryFn: async () => {
            const { data } = await api.projects({ projectId }).get()
            return data ?? null
        },
    })

    const [loadedProjectId, setLoadedProjectId] = useState<number | null>(null)
    const [prompt, setPrompt] = useState('')
    const [negativePrompt, setNegativePrompt] = useState('')
    const [variables, setVariables] = useState<[string, string][]>([])

    const savePromptRef = useRef(
        debounce(async (projectId: number, prompt: string, negativePrompt: string) => {
            const { data } = await api.projects({ projectId }).patch({ prompt, negativePrompt })

            if (data) queryClient.setQueryData(qk.project(projectId), data)
        }, 600),
    )

    const saveVariablesRef = useRef(
        debounce(async (projectId: number, vars: [string, string][]) => {
            const { data } = await api
                .projects({ projectId })
                .patch({ variables: Object.fromEntries(vars) })

            if (data) queryClient.setQueryData(qk.project(projectId), data)
        }, 600),
    )

    // Sync local state when switching projects
    useEffect(() => {
        const data = projectQuery.data
        if (data && data.id !== loadedProjectId) {
            savePromptRef.current.cancel()
            saveVariablesRef.current.cancel()

            setLoadedProjectId(data.id)
            setPrompt(data.prompt ?? '')
            setNegativePrompt(data.negativePrompt ?? '')
            setVariables(Object.entries(data.variables ?? {}))
        }
    }, [projectQuery.data, loadedProjectId])

    // Flush pending saves on unmount
    useEffect(() => {
        return () => {
            savePromptRef.current.flush()
            saveVariablesRef.current.flush()
        }
    }, [])

    function handlePromptChange(value: string) {
        setPrompt(value)
        if (loadedProjectId) savePromptRef.current(loadedProjectId, value, negativePrompt)
    }

    function handleNegativePromptChange(value: string) {
        setNegativePrompt(value)
        if (loadedProjectId) savePromptRef.current(loadedProjectId, prompt, value)
    }

    const project = projectQuery.data

    return (
        <>
            <SidebarHeader className="border-b">
                <div className="flex items-center gap-2 px-1 py-1">
                    <AlignLeft className="h-4 w-4 shrink-0" />
                    <span className="truncate text-md font-bold">
                        {project?.name ?? '프로젝트 선택 안 됨'}
                    </span>
                </div>
            </SidebarHeader>

            {!project ? (
                <div className="flex flex-1 items-center justify-center p-4 text-center text-xs text-muted-foreground">
                    왼쪽 패널에서 프로젝트를 선택하세요
                </div>
            ) : (
                <Tabs defaultValue="prompt" className="flex flex-1 flex-col overflow-hidden">
                    <TabsList className="shrink-0 w-full" variant="line">
                        <TabsTrigger value="prompt" className="flex-1 text-xs">
                            프롬프트
                        </TabsTrigger>
                        <TabsTrigger value="reference" className="flex-1 text-xs">
                            레퍼런스
                        </TabsTrigger>
                    </TabsList>

                    <TabsContent
                        value="prompt"
                        className="flex flex-col flex-1 overflow-hidden px-2 my-4 gap-4 overflow-y-auto scrollbar-none"
                    >
                        <span className="text-lg">프롬프트</span>
                        <PromptEditor
                            prompt={prompt}
                            negativePrompt={negativePrompt}
                            onPromptChange={handlePromptChange}
                            onNegativePromptChange={handleNegativePromptChange}
                            className="min-h-[300px]"
                        />

                        <span className="text-lg mt-4">캐릭터 프롬프트</span>
                        <CharacterPromptEditor
                            projectId={project.id}
                            characterPrompts={project.characterPrompts ?? []}
                        />

                        <span className="text-lg mt-4">변수</span>
                        <PromptVariableEditor variables={variables} onChange={setVariables} />
                    </TabsContent>

                    <TabsContent
                        value="reference"
                        className="flex flex-col flex-1 overflow-hidden px-2 my-4 gap-4 overflow-y-auto scrollbar-none"
                    >
                        <VibeTransferEditor projectId={project.id} />
                    </TabsContent>
                </Tabs>
            )}
        </>
    )
}

// web-next/src/lib/components/app/sidebar/sidebar-prompt.svelte
<script lang="ts">
import { createQuery, useQueryClient } from '@tanstack/svelte-query'
import { AlignLeft, Plus, X } from 'phosphor-svelte'
import { onDestroy } from 'svelte'
import CodeEditor from '$lib/components/app/code-editor.svelte'
import CharacterPromptEditor from '$lib/components/app/project/character-prompt-editor.svelte'
import PromptEditor from '$lib/components/app/project/prompt-editor.svelte'
import { Button } from '$lib/components/ui/button'
import { Input } from '$lib/components/ui/input'
import { ScrollArea } from '$lib/components/ui/scroll-area'
import { SidebarHeader } from '$lib/components/ui/sidebar'
import * as Tabs from '$lib/components/ui/tabs'
import { api } from '$lib/api'
import { qk } from '$lib/query-keys'
import { tagCompletionSource } from '$lib/tag-autocomplete'
import type { CharacterPrompt, ProjectData } from '$lib/types'
import { debounce } from '$lib/utils'

let { projectId }: { projectId: number } = $props()
const queryClient = useQueryClient()

const projectQuery = createQuery(() => ({
    queryKey: qk.project(projectId),
    queryFn: async () => {
        const { data } = await api.projects({ projectId }).get()
        return (data ?? null) as ProjectData | null
    },
}))

let loadedProjectId = $state<number | null>(null)
let prompt = $state('')
let negativePrompt = $state('')
let variables = $state<[string, string][]>([])
let tab = $state('prompt')

const savePrompt = debounce(async (id: number, promptValue: string, negativeValue: string) => {
    const { data } = await api
        .projects({ projectId: id })
        .patch({ prompt: promptValue, negativePrompt: negativeValue })
    if (data) queryClient.setQueryData(qk.project(id), data)
}, 600)

const saveVariables = debounce(async (id: number, vars: [string, string][]) => {
    const { data } = await api
        .projects({ projectId: id })
        .patch({ variables: Object.fromEntries(vars) })
    if (data) queryClient.setQueryData(qk.project(id), data)
}, 600)

$effect(() => {
    const project = projectQuery.data
    if (!project || project.id === loadedProjectId) return
    savePrompt.cancel()
    saveVariables.cancel()
    loadedProjectId = project.id
    prompt = project.prompt ?? ''
    negativePrompt = project.negativePrompt ?? ''
    variables = Object.entries(project.variables ?? {})
})

onDestroy(() => {
    savePrompt.flush()
    saveVariables.flush()
})

function handlePromptChange(value: string) {
    prompt = value
    if (loadedProjectId) savePrompt(loadedProjectId, value, negativePrompt)
}

function handleNegativePromptChange(value: string) {
    negativePrompt = value
    if (loadedProjectId) savePrompt(loadedProjectId, prompt, value)
}

function saveCurrentVariables(next = variables) {
    if (loadedProjectId) saveVariables(loadedProjectId, next)
}

function addVariable() {
    variables = [...variables, ['', '']]
}

function removeVariable(index: number) {
    variables = variables.filter((_, i) => i !== index)
    saveCurrentVariables()
}

function updateVarKey(index: number, key: string) {
    variables = variables.map((item, i) => (i === index ? [key, item[1]] : item)) as [
        string,
        string,
    ][]
}

function updateVarValue(index: number, value: string) {
    variables = variables.map((item, i) => (i === index ? [item[0], value] : item)) as [
        string,
        string,
    ][]
    saveCurrentVariables()
}

const project = $derived(projectQuery.data)
</script>

<SidebarHeader class="border-b">
	<div class="flex items-center gap-2 px-1 py-1">
		<AlignLeft class="h-4 w-4 shrink-0" />
		<span class="truncate text-md font-bold">{project?.name ?? '프로젝트 선택 안 됨'}</span>
	</div>
</SidebarHeader>

{#if !project}
	<div class="flex flex-1 items-center justify-center p-4 text-center text-xs text-muted-foreground">
		왼쪽 패널에서 프로젝트를 선택하세요
	</div>
{:else}
	<Tabs.Root bind:value={tab} class="flex flex-1 flex-col overflow-hidden">
		<Tabs.List class="w-full shrink-0" variant="line">
			<Tabs.Trigger value="prompt" class="flex-1 text-xs">프롬프트</Tabs.Trigger>
			<Tabs.Trigger value="variables" class="flex-1 text-xs">변수</Tabs.Trigger>
			<Tabs.Trigger value="chars" class="flex-1 text-xs">캐릭터</Tabs.Trigger>
		</Tabs.List>

		<Tabs.Content value="prompt" class="flex-1 overflow-hidden px-2 py-1">
			<PromptEditor
				{prompt}
				{negativePrompt}
				onPromptChange={handlePromptChange}
				onNegativePromptChange={handleNegativePromptChange}
				class="min-h-[300px]"
			/>
		</Tabs.Content>

		<Tabs.Content value="variables" class="flex-1 overflow-hidden">
			<ScrollArea class="h-full">
				<div class="flex flex-col gap-2 px-2 pb-2">
					{#each variables as [key, value], index (index)}
						<div class="flex flex-col gap-1">
							<div class="flex items-center gap-1">
								<Input
									class="h-7 flex-1 px-2 font-mono text-xs"
									value={key}
									placeholder="변수명"
									oninput={(event) => updateVarKey(index, event.currentTarget.value)}
									onblur={() => saveCurrentVariables()}
								/>
								<Button
									variant="ghost"
									size="icon-xs"
									class="h-6 w-6 shrink-0"
									onclick={() => removeVariable(index)}
								>
									<X class="h-3 w-3" />
								</Button>
							</div>
							<CodeEditor
								{value}
								placeholder="값 (태그, 프롬프트 등)..."
								minLines={2}
								completionSource={tagCompletionSource}
								onChange={(next) => updateVarValue(index, next)}
							/>
						</div>
					{/each}
					<Button variant="outline" size="sm" class="h-7 gap-1.5 text-xs" onclick={addVariable}>
						<Plus class="h-3.5 w-3.5" />
						변수 추가
					</Button>
				</div>
			</ScrollArea>
		</Tabs.Content>

		<Tabs.Content value="chars" class="flex-1 overflow-hidden">
			<ScrollArea class="h-full">
				<div class="px-2 pb-2">
					<CharacterPromptEditor
						projectId={project.id}
						characterPrompts={(project.characterPrompts as CharacterPrompt[]) ?? []}
					/>
				</div>
			</ScrollArea>
		</Tabs.Content>
	</Tabs.Root>
{/if}
