// web-next/src/components/app/sidebar/sidebar-settings.tsx
import { Link } from '@tanstack/react-router'
import { Settings } from 'lucide-react'
import { Button } from '@/components/ui/button'
import { SidebarContent, SidebarGroup, SidebarGroupContent } from '@/components/ui/sidebar'

export function SidebarSettings() {
    return (
        <SidebarContent>
            <SidebarGroup>
                <SidebarGroupContent className="px-2 pt-2">
                    <Button
                        variant="outline"
                        size="sm"
                        className="gap-1.5 w-full"
                        render={<Link to="/settings" />}
                    >
                        <Settings className="h-3.5 w-3.5" />
                        설정 페이지 열기
                    </Button>
                </SidebarGroupContent>
            </SidebarGroup>
        </SidebarContent>
    )
}

// web-next/src/lib/components/app/sidebar/sidebar-settings.svelte
<script lang="ts">
import { Gear } from 'phosphor-svelte'
import { Button } from '$lib/components/ui/button'
import * as Sidebar from '$lib/components/ui/sidebar'
</script>

<Sidebar.Content>
	<Sidebar.Group>
		<Sidebar.GroupContent class="px-2 pt-2">
			<Button variant="outline" size="sm" class="w-full gap-1.5" href="/settings">
				<Gear class="h-3.5 w-3.5" />
				설정 페이지 열기
			</Button>
		</Sidebar.GroupContent>
	</Sidebar.Group>
</Sidebar.Content>
