// web/src/lib/components/ui/skeleton/skeleton.svelte
<script lang="ts">
    import { cn, type WithElementRef, type WithoutChildren } from '$lib/utils.js'
    import type { HTMLAttributes } from 'svelte/elements'

    let {
        ref = $bindable(null),
        class: className,
        ...restProps
    }: WithoutChildren<WithElementRef<HTMLAttributes<HTMLDivElement>>> = $props()
</script>

<div
    bind:this={ref}
    data-slot="skeleton"
    class={cn('animate-pulse rounded-md bg-accent', className)}
    {...restProps}
></div>

// web/src/components/ui/skeleton.tsx
import { cn } from '#/lib/utils'

function Skeleton({ className, ...props }: React.ComponentProps<'div'>) {
    return (
        <div
            data-slot="skeleton"
            className={cn('animate-pulse rounded-md bg-accent', className)}
            {...props}
        />
    )
}

export { Skeleton }
