// web/src/components/app/header.tsx
import { useRouterState } from '@tanstack/react-router'
import {
    Breadcrumb,
    BreadcrumbItem,
    BreadcrumbLink,
    BreadcrumbList,
    BreadcrumbSeparator,
} from '#/components/ui/breadcrumb'
import { Separator } from '#/components/ui/separator'
import { SidebarTrigger } from '#/components/ui/sidebar'

export function Header() {
    const pathname = useRouterState({ select: (s) => s.location.pathname })

    const parts =
        pathname === '/'
            ? ['Home']
            : pathname
                  .slice(1)
                  .split('/')
                  .map((part) => part.charAt(0).toUpperCase() + part.slice(1))

    return (
        <header className="sticky top-0 flex shrink-0 items-center gap-2 border-b bg-background p-4">
            <SidebarTrigger className="-ms-1" />
            <Separator orientation="vertical" className="me-2 data-[orientation=vertical]:h-4" />
            <Breadcrumb>
                <BreadcrumbList>
                    {parts.map((part, index) => (
                        <BreadcrumbItem key={index}>
                            <BreadcrumbLink href="#">{part}</BreadcrumbLink>
                            {index < parts.length - 1 && <BreadcrumbSeparator />}
                        </BreadcrumbItem>
                    ))}
                </BreadcrumbList>
            </Breadcrumb>
        </header>
    )
}

// web-next/src/lib/components/app/header.svelte
<script lang="ts">
import { page } from '$app/state'
import * as Breadcrumb from '$lib/components/ui/breadcrumb'
import { Separator } from '$lib/components/ui/separator'
import { SidebarTrigger } from '$lib/components/ui/sidebar'

const parts = $derived.by(() => {
    const pathname = page.url.pathname
    if (pathname === '/') return ['Home']
    return pathname
        .slice(1)
        .split('/')
        .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
})
</script>

<header class="sticky top-0 flex shrink-0 items-center gap-2 border-b bg-background p-4">
	<SidebarTrigger class="-ms-1" />
	<Separator orientation="vertical" class="me-2 data-[orientation=vertical]:h-4" />
	<Breadcrumb.Root>
		<Breadcrumb.List>
			{#each parts as part, index}
				<Breadcrumb.Item>
					<Breadcrumb.Link href="#">{part}</Breadcrumb.Link>
					{#if index < parts.length - 1}
						<Breadcrumb.Separator />
					{/if}
				</Breadcrumb.Item>
			{/each}
		</Breadcrumb.List>
	</Breadcrumb.Root>
</header>
