// web/src/components/app/code-editor/code-editor.tsx
import { autocompletion, type CompletionSource } from '@codemirror/autocomplete'
import { defaultKeymap, history, historyKeymap } from '@codemirror/commands'
import { EditorState, type Extension } from '@codemirror/state'
import { placeholder as cmPlaceholder, EditorView, keymap } from '@codemirror/view'
import { useEffect, useRef } from 'react'
import { cn } from '#/lib/utils'
import { shadcnTheme } from './theme'

const LINE_HEIGHT = 19.5
const PADDING_V = 12

interface CodeEditorProps {
    value?: string
    placeholder?: string
    className?: string
    minLines?: number
    completionSource?: CompletionSource
    onChange?: (value: string) => void
}

export function CodeEditor({
    value = '',
    placeholder = '',
    className,
    minLines = 3,
    completionSource,
    onChange,
}: CodeEditorProps) {
    const containerRef = useRef<HTMLDivElement>(null)
    const viewRef = useRef<EditorView | null>(null)
    const onChangeRef = useRef(onChange)
    onChangeRef.current = onChange

    // biome-ignore lint/correctness/useExhaustiveDependencies: intentional one-time editor initialization
    useEffect(() => {
        if (!containerRef.current) return

        const extensions: Extension[] = [
            history(),
            // @ts-ignore
            keymap.of([...defaultKeymap, ...historyKeymap]),
            EditorView.lineWrapping,
            cmPlaceholder(placeholder),
            autocompletion(completionSource ? { override: [completionSource], activateOnTyping: true } : {}),
            shadcnTheme,
            EditorView.updateListener.of((update) => {
                if (update.docChanged) {
                    onChangeRef.current?.(update.state.doc.toString())
                }
            }),
        ]

        const view = new EditorView({
            state: EditorState.create({ doc: value, extensions }),
            parent: containerRef.current,
        })
        viewRef.current = view

        return () => {
            view.destroy()
            viewRef.current = null
        }
        // eslint-disable-next-line react-hooks/exhaustive-deps
    }, [])

    // Sync external value changes without triggering infinite loops
    useEffect(() => {
        const view = viewRef.current
        if (view && view.state.doc.toString() !== value) {
            view.dispatch({
                changes: { from: 0, to: view.state.doc.length, insert: value },
            })
        }
    }, [value])

    return (
        <div
            ref={containerRef}
            className={cn('overflow-hidden rounded-md bg-sidebar min-h-24', className)}
            style={{ minHeight: minLines * LINE_HEIGHT + PADDING_V }}
        />
    )
}

// web/src/lib/components/ui/code-editor/CodeEditor.svelte
<script lang="ts">
    import { onMount, onDestroy } from 'svelte'
    import { EditorView, keymap, placeholder as cmPlaceholder } from '@codemirror/view'
    import { EditorState, type Extension } from '@codemirror/state'
    import { defaultKeymap, historyKeymap, history } from '@codemirror/commands'
    import { autocompletion, type CompletionSource } from '@codemirror/autocomplete'
    import { shadcnTheme } from './theme'
    import { cn } from '$lib/utils'

    let {
        value = $bindable(''),
        placeholder = '',
        class: className = '',
        minLines = 3,
        completionSource,
        onchange,
    }: {
        value?: string
        placeholder?: string
        class?: string
        /** Minimum visible line count (drives min-height). Default: 3 */
        minLines?: number
        /** Optional CodeMirror completion source for autocomplete */
        completionSource?: CompletionSource
        onchange?: (value: string) => void
    } = $props()

    let container: HTMLDivElement
    let view: EditorView | null = null

    function buildExtensions(): Extension[] {
        return [
            history(),
            keymap.of([...defaultKeymap, ...historyKeymap]),
            EditorView.lineWrapping,
            cmPlaceholder(placeholder),
            autocompletion(completionSource ? { override: [completionSource] } : {}),
            shadcnTheme,
            EditorView.updateListener.of((update) => {
                if (update.docChanged) {
                    const v = update.state.doc.toString()
                    value = v
                    onchange?.(v)
                }
            }),
        ]
    }

    onMount(() => {
        view = new EditorView({
            state: EditorState.create({ doc: value, extensions: buildExtensions() }),
            parent: container,
        })
    })

    onDestroy(() => view?.destroy())

    // Sync external value changes into the editor without triggering a loop
    $effect(() => {
        const v = value
        if (view && view.state.doc.toString() !== v) {
            view.dispatch({ changes: { from: 0, to: view.state.doc.length, insert: v } })
        }
    })

    // Approximate line-height in px for min-height calculation (matches lineHeight: 1.5 * 13px)
    const LINE_HEIGHT = 19.5
    const PADDING_V = 12 // top + bottom padding
</script>

<div
    bind:this={container}
    class={cn(
        'overflow-hidden rounded-md border border-input bg-background',
        className,
    )}
    style="min-height: {minLines * LINE_HEIGHT + PADDING_V}px"
></div>
