// web-next/src/components/app/sidebar/sidebar-header.tsx
import { Link } from '@tanstack/react-router'
import { Factory } from 'lucide-react'
import * as Base from '@/components/ui/sidebar'

export function SidebarHeader() {
    return (
        <Base.SidebarHeader>
            <Base.SidebarMenu>
                <Base.SidebarMenuItem>
                    <Base.SidebarMenuButton
                        size="lg"
                        className="md:h-8 md:p-0"
                        render={<Link to="/" />}
                    >
                        <div className="flex aspect-square size-8 items-center justify-center rounded-lg bg-sidebar-primary text-sidebar-primary-foreground">
                            <Factory className="size-4" />
                        </div>
                        <div className="grid flex-1 text-left text-sm leading-tight">
                            <span className="truncate font-semibold">NAI Factory</span>
                            <span className="truncate text-xs">Local</span>
                        </div>
                    </Base.SidebarMenuButton>
                </Base.SidebarMenuItem>
            </Base.SidebarMenu>
        </Base.SidebarHeader>
    )
}

// web/src/lib/components/app/sidebar/sidebar-header.svelte
<script lang="ts">
    import FactoryIcon from '@lucide/svelte/icons/factory'
    import * as Sidebar from '$lib/components/ui/sidebar'
</script>

<Sidebar.Header>
    <Sidebar.Menu>
        <Sidebar.MenuItem>
            <Sidebar.MenuButton size="lg" class="md:h-8 md:p-0">
                {#snippet child({ props })}
                    <a href="/" {...props}>
                        <div
                            class="flex aspect-square size-8 items-center justify-center rounded-lg bg-sidebar-primary text-sidebar-primary-foreground"
                        >
                            <FactoryIcon class="size-4" />
                        </div>
                        <div class="grid flex-1 text-start text-sm leading-tight">
                            <span class="truncate font-medium">NAI Factory</span>
                            <span class="truncate text-xs">Local</span>
                        </div>
                    </a>
                {/snippet}
            </Sidebar.MenuButton>
        </Sidebar.MenuItem>
    </Sidebar.Menu>
</Sidebar.Header>
