// web-next/src/lib/components/app/code-editor.svelte
<script lang="ts">
import { acceptCompletion, autocompletion, type CompletionSource } from '@codemirror/autocomplete'
import { defaultKeymap, history, historyKeymap } from '@codemirror/commands'
import { EditorState, type Extension } from '@codemirror/state'
import { EditorView, keymap, placeholder as cmPlaceholder, tooltips } from '@codemirror/view'
import { onDestroy, onMount } from 'svelte'
import { cn } from '$lib/utils'
import { shadcnTheme } from '../../theme'

const lineHeight = 19.5
const paddingY = 12

let {
    value = $bindable(''),
    placeholder = '',
    class: className,
    minLines = 3,
    completionSource,
    onChange,
}: {
    value?: string
    placeholder?: string
    class?: string
    minLines?: number
    completionSource?: CompletionSource
    onChange?: (value: string) => void
} = $props()

let container: HTMLDivElement
let view: EditorView | null = null
let focused = $state(false)
let externalValue = $derived(value)

onMount(() => {
    const extensions: Extension[] = [
        history(),
        keymap.of([
            { key: 'Tab', run: acceptCompletion },
            ...defaultKeymap,
            ...historyKeymap,
        ] as any),
        EditorView.lineWrapping,
        cmPlaceholder(placeholder),
        autocompletion({
            override: [(ctx) => completionSource?.(ctx) ?? null],
            activateOnTyping: true,
        }),
        tooltips({ parent: document.body }),
        shadcnTheme,
        EditorView.focusChangeEffect.of((_, isFocused) => {
            focused = isFocused
            return null
        }),
        EditorView.updateListener.of((update) => {
            if (!update.docChanged) return
            value = update.state.doc.toString()
            onChange?.(value)
        }),
    ]

    view = new EditorView({
        state: EditorState.create({ doc: value, extensions }),
        parent: container,
    })
})

$effect(() => {
    if (!view || focused) return
    const current = view.state.doc.toString()
    if (current !== externalValue) {
        view.dispatch({ changes: { from: 0, to: current.length, insert: externalValue } })
    }
})

onDestroy(() => {
    view?.destroy()
    view = null
})
</script>

<div
	bind:this={container}
	class={cn('min-h-24 overflow-hidden rounded-md bg-sidebar', className)}
	style:min-height={`${minLines * lineHeight + paddingY}px`}
></div>

// web/src/components/app/code-editor/code-editor.tsx
import { autocompletion, type CompletionSource } from '@codemirror/autocomplete'
import { defaultKeymap, history, historyKeymap } from '@codemirror/commands'
import { EditorState, type Extension } from '@codemirror/state'
import { placeholder as cmPlaceholder, EditorView, keymap } from '@codemirror/view'
import { useEffect, useRef } from 'react'
import { cn } from '#/lib/utils'
import { shadcnTheme } from './theme'

const LINE_HEIGHT = 19.5
const PADDING_V = 12

interface CodeEditorProps {
    value?: string
    placeholder?: string
    className?: string
    minLines?: number
    completionSource?: CompletionSource
    onChange?: (value: string) => void
}

export function CodeEditor({
    value = '',
    placeholder = '',
    className,
    minLines = 3,
    completionSource,
    onChange,
}: CodeEditorProps) {
    const containerRef = useRef<HTMLDivElement>(null)
    const viewRef = useRef<EditorView | null>(null)
    const onChangeRef = useRef(onChange)
    onChangeRef.current = onChange

    // biome-ignore lint/correctness/useExhaustiveDependencies: intentional one-time editor initialization
    useEffect(() => {
        if (!containerRef.current) return

        const extensions: Extension[] = [
            history(),
            // @ts-ignore
            keymap.of([...defaultKeymap, ...historyKeymap]),
            EditorView.lineWrapping,
            cmPlaceholder(placeholder),
            autocompletion(completionSource ? { override: [completionSource], activateOnTyping: true } : {}),
            shadcnTheme,
            EditorView.updateListener.of((update) => {
                if (update.docChanged) {
                    onChangeRef.current?.(update.state.doc.toString())
                }
            }),
        ]

        const view = new EditorView({
            state: EditorState.create({ doc: value, extensions }),
            parent: containerRef.current,
        })
        viewRef.current = view

        return () => {
            view.destroy()
            viewRef.current = null
        }
        // eslint-disable-next-line react-hooks/exhaustive-deps
    }, [])

    // Sync external value changes without triggering infinite loops
    useEffect(() => {
        const view = viewRef.current
        if (view && view.state.doc.toString() !== value) {
            view.dispatch({
                changes: { from: 0, to: view.state.doc.length, insert: value },
            })
        }
    }, [value])

    return (
        <div
            ref={containerRef}
            className={cn('overflow-hidden rounded-md bg-sidebar min-h-24', className)}
            style={{ minHeight: minLines * LINE_HEIGHT + PADDING_V }}
        />
    )
}
