// web-next/src/components/app/project/sortable-image-item.tsx
import { useSortable } from '@dnd-kit/sortable'
import { CSS } from '@dnd-kit/utilities'
import { Trash2 } from 'lucide-react'
import { Button } from '@/components/ui/button'

type Image = {
    id: number
    filePath: string
    thumbnailPath?: string | null
}

interface SortableImageItemProps {
    img: Image
    imageUrl: string
    onView: (img: Image) => void
    onDelete: (img: Image) => void
}

export function SortableImageItem({ img, imageUrl, onView, onDelete }: SortableImageItemProps) {
    const { attributes, listeners, setNodeRef, transform, transition, isDragging } = useSortable({
        id: img.id,
    })

    const style = {
        transform: CSS.Transform.toString(transform),
        transition,
        opacity: isDragging ? 0.4 : 1,
    }

    return (
        <div ref={setNodeRef} style={style} className="group relative aspect-[3/4] cursor-pointer">
            <button
                className="h-full w-full overflow-hidden rounded-lg border bg-muted"
                onClick={() => onView(img)}
                {...attributes}
                {...listeners}
            >
                <img
                    src={imageUrl}
                    alt=""
                    className="h-full w-full object-cover transition-transform duration-200 group-hover:scale-105"
                    loading="lazy"
                    draggable={false}
                />
            </button>

            <Button
                variant="ghost"
                size="icon"
                className="absolute top-1.5 right-1.5 hidden h-7 w-7 rounded-full bg-black/50 text-white hover:bg-black/70 group-hover:flex"
                onClick={(e) => {
                    e.stopPropagation()
                    onDelete(img)
                }}
            >
                <Trash2 className="h-3.5 w-3.5" />
            </Button>
        </div>
    )
}

// web-next/src/lib/components/app/project/sortable-image-item.svelte
<script lang="ts">
import { createSortable } from '@dnd-kit/svelte/sortable'
import { Trash } from 'phosphor-svelte'
import { Button } from '$lib/components/ui/button'
import type { ImageItem } from '$lib/types'

let {
    img,
    index,
    src,
    onView,
    onDelete,
}: {
    img: ImageItem
    index: number
    src: string
    onView: (img: ImageItem) => void
    onDelete: (img: ImageItem) => void
} = $props()

// svelte-ignore state_referenced_locally
const sortable = createSortable({
	get id() { return img.id },
	get index() { return index },
	group: 'images'
})
</script>

<div
	{@attach sortable.attach}
	class="group relative aspect-[3/4] cursor-pointer"
	class:opacity-40={sortable.isDragging}
>
	<button
		type="button"
		class="h-full w-full overflow-hidden rounded-lg border bg-muted"
		onclick={() => onView(img)}
		{@attach sortable.attachHandle}
	>
		<img
			{src}
			alt=""
			class="h-full w-full object-cover transition-transform duration-200 group-hover:scale-105"
			loading="lazy"
			draggable="false"
		/>
	</button>

	<Button
		variant="ghost"
		size="icon-sm"
		class="absolute top-1.5 right-1.5 hidden h-7 w-7 rounded-full bg-black/50 text-white hover:bg-black/70 group-hover:flex"
		onclick={(event) => {
			event.stopPropagation()
			onDelete(img)
		}}
	>
		<Trash class="h-3.5 w-3.5" />
	</Button>
</div>
