// web/src/features/project/sortable-scene-item.tsx
import { useSortable } from '@dnd-kit/sortable'
import { CSS } from '@dnd-kit/utilities'
import type { ProjectSettings } from '@nai-factory/shared'
import type { SceneSummary } from '@nai-factory/shared'
import { GripHorizontal } from 'lucide-react'

import { SceneCard } from './scene-card'

interface SortableSceneItemProps {
    scene: SceneSummary
    index: number
    selected: boolean
    selectMode: boolean
    isProcessing: boolean
    slideshowCount: number
    cardSize: ProjectSettings['sceneCardSize']
    onToggleSelect: (id: number) => void
    onSelectDragStart: (index: number, selected: boolean) => void
    onSelectDragEnter: (index: number) => void
}

export function SortableSceneItem({
    scene,
    index,
    selected,
    selectMode,
    isProcessing,
    slideshowCount,
    cardSize,
    onToggleSelect,
    onSelectDragStart,
    onSelectDragEnter,
}: SortableSceneItemProps) {
    const { attributes, listeners, setNodeRef, transform, isDragging } = useSortable({
        id: scene.id,
        animateLayoutChanges: () => false,
    })

    const style = {
        transform: CSS.Transform.toString(transform),
        transition: 'none',
    }

    return (
        <div
            ref={setNodeRef}
            style={style}
            className={`group/scene-item relative ${isDragging ? 'opacity-40' : ''}`}
            onPointerEnter={() => onSelectDragEnter(index)}
        >
            <SceneCard
                scene={scene}
                index={index}
                selected={selected}
                selectMode={selectMode}
                isProcessing={isProcessing}
                slideshowCount={slideshowCount}
                cardSize={cardSize}
                onToggleSelect={onToggleSelect}
                onSelectDragStart={onSelectDragStart}
            />

            <div
                {...attributes}
                {...listeners}
                className="pointer-events-none absolute top-1 left-1/2 z-30 flex -translate-x-1/2 cursor-grab items-center justify-center rounded bg-black/50 px-3 py-1 opacity-0 transition-opacity group-hover/scene-item:pointer-events-auto group-hover/scene-item:opacity-100 active:cursor-grabbing [@media(hover:none)]:pointer-events-auto [@media(hover:none)]:opacity-100"
            >
                <GripHorizontal className="h-3.5 w-3.5 text-white" />
            </div>
        </div>
    )
}

// web-next/src/lib/components/app/project/sortable-scene-item.svelte
<script lang="ts">
import { createSortable } from '@dnd-kit/svelte/sortable'
import { DotsSix } from 'phosphor-svelte'
import type { Scene } from '$lib/types'
import SceneCard from './scene-card.svelte'

let {
    scene,
    index,
    selected,
    selectMode,
    isProcessing,
    slideshowCount,
    onToggleSelect,
}: {
    scene: Scene
    index: number
    selected: boolean
    selectMode: boolean
    isProcessing: boolean
    slideshowCount: number
    onToggleSelect: (id: number) => void
} = $props()

// svelte-ignore state_referenced_locally
const sortable = createSortable({
	get id() { return scene.id },
	get index() { return index },
	group: 'scenes'
})
</script>

<div
	{@attach sortable.attach}
	class={`group relative ${sortable.isDragging ? 'opacity-40' : ''}`}
>
	<SceneCard
		{scene}
		{selected}
		{selectMode}
		{isProcessing}
		{slideshowCount}
		{onToggleSelect}
	/>
	<div
		{@attach sortable.attachHandle}
		class="absolute left-1/2 top-1 z-30 flex -translate-x-1/2 cursor-grab items-center justify-center rounded bg-black/50 px-2 py-0.5 opacity-0 transition-opacity group-hover:opacity-100 active:cursor-grabbing"
	>
		<DotsSix class="h-3.5 w-3.5 text-white" />
	</div>
</div>
