// web/src/lib/components/app/sidebar/sidebar-project.svelte
<script lang="ts">
    import ChevronRightIcon from '@lucide/svelte/icons/chevron-right'
    import FolderIcon from '@lucide/svelte/icons/folder'
    import FileIcon from '@lucide/svelte/icons/file'
    import PlusIcon from '@lucide/svelte/icons/plus'
    import MoreHorizontalIcon from '@lucide/svelte/icons/more-horizontal'
    import * as Collapsible from '$lib/components/ui/collapsible'
    import * as Sidebar from '$lib/components/ui/sidebar'
    import * as DropdownMenu from '$lib/components/ui/dropdown-menu'
    import { Button } from '$lib/components/ui/button'
    import { api } from '$lib/api'
    import { goto } from '$app/navigation'
    import { page } from '$app/state'
    import { selectedProject } from '$lib/states/selected-project.svelte'
    import CreateGroupDialog from '$lib/components/app/dialogs/create-group-dialog.svelte'
    import CreateProjectDialog from '$lib/components/app/dialogs/create-project-dialog.svelte'
    import ConfirmDeleteDialog from '$lib/components/app/dialogs/confirm-delete-dialog.svelte'
    import { Input } from '$lib/components/ui/input'
    import { createQuery, createMutation, useQueryClient } from '@tanstack/svelte-query'
    import { qk } from '$lib/queries'

    type Group = NonNullable<Awaited<ReturnType<typeof api.api.groups.get>>['data']>[number]
    type Project = NonNullable<
        Awaited<ReturnType<typeof api.api.projects.get>>['data']
    >[number]
    type GroupWithProjects = Group & { projects: Project[] }

    const queryClient = useQueryClient()

    const groupsQuery = createQuery(() => ({
        queryKey: qk.groupsWithProjects(),
        queryFn: async () => {
            const { data } = await api.api.groups.get()
            if (!data) return [] as GroupWithProjects[]
            return Promise.all(
                data.map(async (g) => {
                    const { data: projects } = await api.api.projects.get({
                        query: { groupId: g.id },
                    })
                    return { ...g, projects: projects ?? [] } as GroupWithProjects
                }),
            )
        },
    }))

    function invalidateGroups() {
        queryClient.invalidateQueries({ queryKey: qk.groupsWithProjects() })
    }

    const createGroup = createMutation(() => ({
        mutationFn: (name: string) => api.api.groups.post({ name }),
        onSuccess: invalidateGroups,
    }))

    const deleteGroup = createMutation(() => ({
        mutationFn: (id: number) => api.api.groups({ id }).delete(),
        onSuccess: invalidateGroups,
    }))

    const renameGroup = createMutation(() => ({
        mutationFn: ({ id, name }: { id: number; name: string }) =>
            api.api.groups({ id }).patch({ name }),
        onSuccess: invalidateGroups,
    }))

    const createProject = createMutation(() => ({
        mutationFn: ({ groupId, name }: { groupId: number; name: string }) =>
            api.api.projects.post({ groupId, name }),
        onSuccess: invalidateGroups,
    }))

    const deleteProject = createMutation(() => ({
        mutationFn: (projectId: number) => api.api.projects({ projectId }).delete(),
        onSuccess: invalidateGroups,
    }))

    const renameProject = createMutation(() => ({
        mutationFn: ({ projectId, name }: { projectId: number; name: string }) =>
            api.api.projects({ projectId }).patch({ name }),
        onSuccess: invalidateGroups,
    }))

    const duplicateProject = createMutation(() => ({
        mutationFn: (projectId: number) =>
            api.api.projects({ projectId }).duplicate.post(),
        onSuccess: invalidateGroups,
    }))

    // Dialogs
    let createGroupOpen = $state(false)
    let createProjectOpen = $state(false)
    let deleteOpen = $state(false)
    let targetGroup = $state<GroupWithProjects | null>(null)
    let targetProject = $state<Project | null>(null)
    let deleteTarget = $state<{ type: 'group' | 'project'; name: string } | null>(null)

    // Rename inline editing
    let renamingGroupId = $state<number | null>(null)
    let renamingProjectId = $state<number | null>(null)
    let renameValue = $state('')

    async function handleDeleteGroup(group: GroupWithProjects) {
        await deleteGroup.mutateAsync(group.id)
        if (selectedProject.id && group.projects.some((p) => p.id === selectedProject.id)) {
            selectedProject.id = null
        }
    }

    async function handleDeleteProject(project: Project) {
        await deleteProject.mutateAsync(project.id)
        if (selectedProject.id === project.id) {
            selectedProject.id = null
            goto('/')
        }
    }

    async function commitGroupRename() {
        if (!renamingGroupId || !renameValue.trim()) { renamingGroupId = null; return }
        await renameGroup.mutateAsync({ id: renamingGroupId, name: renameValue.trim() })
        renamingGroupId = null
    }

    async function commitProjectRename() {
        if (!renamingProjectId || !renameValue.trim()) { renamingProjectId = null; return }
        await renameProject.mutateAsync({ projectId: renamingProjectId, name: renameValue.trim() })
        renamingProjectId = null
    }

    let groups = $derived(groupsQuery.data ?? [])

    let currentProjectId = $derived(
        page.url.pathname.startsWith('/project/')
            ? Number(page.url.pathname.split('/')[2])
            : null,
    )
</script>

<Sidebar.Content>
    <Sidebar.Group>
        <Sidebar.GroupLabel class="flex items-center justify-between pr-1">
            <span>프로젝트</span>
            <button
                class="rounded p-0.5 hover:bg-sidebar-accent"
                onclick={() => (createGroupOpen = true)}
                title="새 그룹"
            >
                <PlusIcon class="h-3.5 w-3.5" />
            </button>
        </Sidebar.GroupLabel>
        <Sidebar.GroupContent>
            <Sidebar.Menu>
                {#if groupsQuery.isPending}
                    <div class="px-2 py-4 text-center text-xs text-muted-foreground">불러오는 중...</div>
                {:else if groups.length === 0}
                    <div class="px-2 py-4 text-center text-xs text-muted-foreground">
                        그룹이 없습니다
                    </div>
                {:else}
                    {#each groups as group (group.id)}
                        <Sidebar.MenuItem>
                            <Collapsible.Root
                                class="group/collapsible [&[data-state=open]>div>button>svg.chevron]:rotate-90"
                                open
                            >
                                <div class="flex items-center gap-0.5 pr-1">
                                    <Collapsible.Trigger class="flex flex-1 items-center gap-1">
                                        {#snippet child({ props })}
                                            <button
                                                {...props}
                                                class="flex flex-1 items-center gap-1 rounded px-2 py-1 text-sm hover:bg-sidebar-accent"
                                            >
                                                <ChevronRightIcon
                                                    class="chevron h-3.5 w-3.5 shrink-0 text-muted-foreground transition-transform"
                                                />
                                                <FolderIcon class="h-3.5 w-3.5 shrink-0" />
                                                {#if renamingGroupId === group.id}
                                                    <Input
                                                        class="h-5 flex-1 px-1 py-0 text-xs"
                                                        value={renameValue}
                                                        oninput={(e) => (renameValue = (e.target as HTMLInputElement).value)}
                                                        onblur={commitGroupRename}
                                                        onkeydown={(e) => {
                                                            if (e.key === 'Enter') commitGroupRename()
                                                            if (e.key === 'Escape') renamingGroupId = null
                                                        }}
                                                        autofocus
                                                        onclick={(e) => e.stopPropagation()}
                                                    />
                                                {:else}
                                                    <span class="truncate text-xs">{group.name}</span>
                                                {/if}
                                            </button>
                                        {/snippet}
                                    </Collapsible.Trigger>

                                    <DropdownMenu.Root>
                                        <DropdownMenu.Trigger>
                                            {#snippet child({ props })}
                                                <Button
                                                    {...props}
                                                    variant="ghost"
                                                    size="icon"
                                                    class="h-6 w-6 shrink-0 opacity-0 group-hover/collapsible:opacity-100"
                                                >
                                                    <MoreHorizontalIcon class="h-3.5 w-3.5" />
                                                </Button>
                                            {/snippet}
                                        </DropdownMenu.Trigger>
                                        <DropdownMenu.Content align="start">
                                            <DropdownMenu.Item
                                                onclick={() => {
                                                    targetGroup = group
                                                    createProjectOpen = true
                                                }}
                                            >
                                                새 프로젝트
                                            </DropdownMenu.Item>
                                            <DropdownMenu.Item
                                                onclick={() => {
                                                    renamingGroupId = group.id
                                                    renameValue = group.name
                                                }}
                                            >
                                                이름 변경
                                            </DropdownMenu.Item>
                                            <DropdownMenu.Separator />
                                            <DropdownMenu.Item
                                                class="text-destructive"
                                                onclick={() => {
                                                    deleteTarget = { type: 'group', name: group.name }
                                                    deleteOpen = true
                                                }}
                                            >
                                                삭제
                                            </DropdownMenu.Item>
                                        </DropdownMenu.Content>
                                    </DropdownMenu.Root>
                                </div>

                                <Collapsible.Content>
                                    <Sidebar.MenuSub>
                                        {#each group.projects as project (project.id)}
                                            <Sidebar.MenuSubItem>
                                                <div class="group/project flex items-center gap-0.5 pr-1">
                                                    {#if renamingProjectId === project.id}
                                                        <Input
                                                            class="h-6 flex-1 px-1 py-0 text-xs"
                                                            value={renameValue}
                                                            oninput={(e) => (renameValue = (e.target as HTMLInputElement).value)}
                                                            onblur={commitProjectRename}
                                                            onkeydown={(e) => {
                                                                if (e.key === 'Enter') commitProjectRename()
                                                                if (e.key === 'Escape') renamingProjectId = null
                                                            }}
                                                            autofocus
                                                        />
                                                    {:else}
                                                        <Sidebar.MenuSubButton
                                                            isActive={currentProjectId === project.id}
                                                            class="flex-1"
                                                            onclick={() => {
                                                                selectedProject.id = project.id
                                                                goto(`/project/${project.id}`)
                                                            }}
                                                        >
                                                            <FileIcon class="h-3.5 w-3.5 shrink-0" />
                                                            <span class="truncate">{project.name}</span>
                                                        </Sidebar.MenuSubButton>
                                                    {/if}

                                                    <DropdownMenu.Root>
                                                        <DropdownMenu.Trigger>
                                                            {#snippet child({ props })}
                                                                <Button
                                                                    {...props}
                                                                    variant="ghost"
                                                                    size="icon"
                                                                    class="h-6 w-6 shrink-0 opacity-0 group-hover/project:opacity-100"
                                                                >
                                                                    <MoreHorizontalIcon
                                                                        class="h-3.5 w-3.5"
                                                                    />
                                                                </Button>
                                                            {/snippet}
                                                        </DropdownMenu.Trigger>
                                                        <DropdownMenu.Content align="start">
                                                            <DropdownMenu.Item
                                                                onclick={() => {
                                                                    renamingProjectId = project.id
                                                                    renameValue = project.name
                                                                }}
                                                            >
                                                                이름 변경
                                                            </DropdownMenu.Item>
                                                            <DropdownMenu.Item
                                                                onclick={() => duplicateProject.mutate(project.id)}
                                                            >
                                                                복제
                                                            </DropdownMenu.Item>
                                                            <DropdownMenu.Separator />
                                                            <DropdownMenu.Item
                                                                class="text-destructive"
                                                                onclick={() => {
                                                                    targetProject = project
                                                                    deleteTarget = {
                                                                        type: 'project',
                                                                        name: project.name,
                                                                    }
                                                                    deleteOpen = true
                                                                }}
                                                            >
                                                                삭제
                                                            </DropdownMenu.Item>
                                                        </DropdownMenu.Content>
                                                    </DropdownMenu.Root>
                                                </div>
                                            </Sidebar.MenuSubItem>
                                        {:else}
                                            <div class="py-1 pl-8 text-xs text-muted-foreground">
                                                프로젝트 없음
                                            </div>
                                        {/each}
                                    </Sidebar.MenuSub>
                                </Collapsible.Content>
                            </Collapsible.Root>
                        </Sidebar.MenuItem>
                    {/each}
                {/if}
            </Sidebar.Menu>
        </Sidebar.GroupContent>
    </Sidebar.Group>
</Sidebar.Content>

<!-- Dialogs -->
<CreateGroupDialog
    bind:open={createGroupOpen}
    oncreate={(name) => createGroup.mutate(name)}
/>

<CreateProjectDialog
    bind:open={createProjectOpen}
    groupName={targetGroup?.name}
    oncreate={(name) => targetGroup && createProject.mutate({ groupId: targetGroup.id, name })}
/>

<ConfirmDeleteDialog
    bind:open={deleteOpen}
    title={deleteTarget?.type === 'group' ? '그룹 삭제' : '프로젝트 삭제'}
    description={`"${deleteTarget?.name}" ${deleteTarget?.type === 'group' ? '그룹과 포함된 모든 프로젝트를 삭제합니다.' : '프로젝트와 모든 씬, 이미지를 삭제합니다.'} 이 작업은 되돌릴 수 없습니다.`}
    onconfirm={() => {
        if (deleteTarget?.type === 'group' && targetGroup) handleDeleteGroup(targetGroup)
        else if (deleteTarget?.type === 'project' && targetProject) handleDeleteProject(targetProject)
    }}
/>

// web-next/src/components/app/sidebar/sidebar-project.tsx
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { useNavigate, useRouterState } from '@tanstack/react-router'
import { ChevronRight, File, Folder, MoreHorizontal, Plus } from 'lucide-react'
import { useState } from 'react'
import { ConfirmDeleteDialog } from '@/components/app/dialogs/confirm-delete-dialog'
import { CreateGroupDialog } from '@/components/app/dialogs/create-group-dialog'
import { CreateProjectDialog } from '@/components/app/dialogs/create-project-dialog'
import { Button } from '@/components/ui/button'
import { Collapsible, CollapsibleContent, CollapsibleTrigger } from '@/components/ui/collapsible'
import {
    DropdownMenu,
    DropdownMenuContent,
    DropdownMenuItem,
    DropdownMenuSeparator,
    DropdownMenuTrigger,
} from '@/components/ui/dropdown-menu'
import { Input } from '@/components/ui/input'
import * as Base from '@/components/ui/sidebar'
import type { GroupWithProjects } from '@/lib/api'
import { api } from '@/lib/api'
import { qk } from '@/lib/queries'

export function SidebarProject() {
    const navigate = useNavigate()
    const pathname = useRouterState({ select: (s) => s.location.pathname })
    const queryClient = useQueryClient()

    const groupsQuery = useQuery({
        queryKey: qk.groupsWithProjects(),
        queryFn: async () => {
            const { data } = await api.groups.get()
            return data ?? []
        },
    })

    function invalidateGroups() {
        queryClient.invalidateQueries({ queryKey: qk.groupsWithProjects() })
    }

    const createGroup = useMutation({
        mutationFn: (name: string) => api.groups.post({ name }),
        onSuccess: invalidateGroups,
    })

    const deleteGroup = useMutation({
        mutationFn: (id: number) => api.groups({ id }).delete(),
        onSuccess: invalidateGroups,
    })

    const renameGroup = useMutation({
        mutationFn: ({ id, name }: { id: number; name: string }) =>
            api.groups({ id }).patch({ name }),
        onSuccess: invalidateGroups,
    })

    const createProject = useMutation({
        mutationFn: ({ groupId, name }: { groupId: number; name: string }) =>
            api.projects.post({ groupId, name }),
        onSuccess: invalidateGroups,
    })

    const deleteProject = useMutation({
        mutationFn: (projectId: number) => api.projects({ projectId }).delete(),
        onSuccess: invalidateGroups,
    })

    const renameProject = useMutation({
        mutationFn: ({ projectId, name }: { projectId: number; name: string }) =>
            api.projects({ projectId }).patch({ name }),
        onSuccess: invalidateGroups,
    })

    const duplicateProject = useMutation({
        mutationFn: (projectId: number) => api.projects({ projectId }).duplicate.post(),
        onSuccess: invalidateGroups,
    })

    const [createGroupOpen, setCreateGroupOpen] = useState(false)
    const [createProjectOpen, setCreateProjectOpen] = useState(false)
    const [deleteOpen, setDeleteOpen] = useState(false)
    const [targetGroup, setTargetGroup] = useState<GroupWithProjects | null>(null)
    const [targetProject, setTargetProject] = useState<{ id: number; name: string } | null>(null)
    const [deleteTarget, setDeleteTarget] = useState<{
        type: 'group' | 'project'
        name: string
    } | null>(null)
    const [renamingGroupId, setRenamingGroupId] = useState<number | null>(null)
    const [renamingProjectId, setRenamingProjectId] = useState<number | null>(null)
    const [renameValue, setRenameValue] = useState('')

    const currentProjectId = pathname.startsWith('/project/')
        ? Number(pathname.split('/')[2])
        : null

    async function handleDeleteGroup(group: GroupWithProjects) {
        await deleteGroup.mutateAsync(group.id)
        if (currentProjectId && group.projects.some((p) => p.id === currentProjectId)) {
            navigate({ to: '/' })
        }
    }

    async function handleDeleteProject(project: { id: number; name: string }) {
        await deleteProject.mutateAsync(project.id)
        if (currentProjectId === project.id) {
            navigate({ to: '/' })
        }
    }

    async function commitGroupRename() {
        if (!renamingGroupId || !renameValue.trim()) {
            setRenamingGroupId(null)
            return
        }
        await renameGroup.mutateAsync({ id: renamingGroupId, name: renameValue.trim() })
        setRenamingGroupId(null)
    }

    async function commitProjectRename() {
        if (!renamingProjectId || !renameValue.trim()) {
            setRenamingProjectId(null)
            return
        }
        await renameProject.mutateAsync({ projectId: renamingProjectId, name: renameValue.trim() })
        setRenamingProjectId(null)
    }

    const groups = groupsQuery.data ?? []

    return (
        <>
            <Base.SidebarContent>
                <Base.SidebarGroup>
                    <Base.SidebarGroupLabel className="flex items-center justify-between pr-1">
                        <span>프로젝트</span>
                        <button
                            type="button"
                            className="rounded p-0.5 hover:bg-sidebar-accent"
                            onClick={() => setCreateGroupOpen(true)}
                        >
                            <Plus className="h-3.5 w-3.5" />
                        </button>
                    </Base.SidebarGroupLabel>
                    <Base.SidebarGroupContent>
                        <Base.SidebarMenu>
                            {groupsQuery.isPending ? (
                                <div className="px-2 py-4 text-center text-xs text-muted-foreground">
                                    불러오는 중...
                                </div>
                            ) : groups.length === 0 ? (
                                <div className="px-2 py-4 text-center text-xs text-muted-foreground">
                                    그룹이 없습니다
                                </div>
                            ) : (
                                groups.map((group) => (
                                    <Base.SidebarMenuItem key={group.id}>
                                        <Collapsible defaultOpen className="group/collapsible">
                                            <div className="flex items-center gap-0.5 pr-1">
                                                <CollapsibleTrigger
                                                    render={
                                                        <button
                                                            type="button"
                                                            className="flex flex-1 items-center gap-1 rounded px-2 py-1 text-sm hover:bg-sidebar-accent"
                                                        />
                                                    }
                                                >
                                                    <ChevronRight className="chevron h-3.5 w-3.5 shrink-0 text-muted-foreground transition-transform group-data-[state=open]/collapsible:rotate-90" />
                                                    <Folder className="h-3.5 w-3.5 shrink-0" />
                                                    {renamingGroupId === group.id ? (
                                                        <Input
                                                            className="h-5 flex-1 px-1 py-0 text-xs"
                                                            value={renameValue}
                                                            onChange={(e) =>
                                                                setRenameValue(e.target.value)
                                                            }
                                                            onBlur={commitGroupRename}
                                                            onKeyDown={(e) => {
                                                                if (e.key === 'Enter')
                                                                    commitGroupRename()
                                                                if (e.key === 'Escape')
                                                                    setRenamingGroupId(null)
                                                            }}
                                                            autoFocus
                                                            onClick={(e) => e.stopPropagation()}
                                                        />
                                                    ) : (
                                                        <span className="truncate text-xs">
                                                            {group.name}
                                                        </span>
                                                    )}
                                                </CollapsibleTrigger>

                                                <DropdownMenu>
                                                    <DropdownMenuTrigger
                                                        render={
                                                            <Button
                                                                variant="ghost"
                                                                size="icon"
                                                                className="h-6 w-6 shrink-0 opacity-0 group-hover/collapsible:opacity-100"
                                                            />
                                                        }
                                                    >
                                                        <MoreHorizontal className="h-3.5 w-3.5" />
                                                    </DropdownMenuTrigger>
                                                    <DropdownMenuContent align="start">
                                                        <DropdownMenuItem
                                                            onClick={() => {
                                                                setTargetGroup(group)
                                                                setCreateProjectOpen(true)
                                                            }}
                                                        >
                                                            새 프로젝트
                                                        </DropdownMenuItem>
                                                        <DropdownMenuItem
                                                            onClick={() => {
                                                                setRenamingGroupId(group.id)
                                                                setRenameValue(group.name)
                                                            }}
                                                        >
                                                            이름 변경
                                                        </DropdownMenuItem>
                                                        <DropdownMenuSeparator />
                                                        <DropdownMenuItem
                                                            className="text-destructive focus:text-destructive"
                                                            onClick={() => {
                                                                setTargetGroup(group)
                                                                setDeleteTarget({
                                                                    type: 'group',
                                                                    name: group.name,
                                                                })
                                                                setDeleteOpen(true)
                                                            }}
                                                        >
                                                            삭제
                                                        </DropdownMenuItem>
                                                    </DropdownMenuContent>
                                                </DropdownMenu>
                                            </div>

                                            <CollapsibleContent>
                                                <Base.SidebarMenuSub>
                                                    {group.projects.length === 0 ? (
                                                        <div className="py-1 pl-8 text-xs text-muted-foreground">
                                                            프로젝트 없음
                                                        </div>
                                                    ) : (
                                                        group.projects.map((project) => (
                                                            <Base.SidebarMenuSubItem
                                                                key={project.id}
                                                            >
                                                                <div className="group/project flex items-center gap-0.5 pr-1">
                                                                    {renamingProjectId ===
                                                                    project.id ? (
                                                                        <Input
                                                                            className="h-6 flex-1 px-1 py-0 text-xs"
                                                                            value={renameValue}
                                                                            onChange={(e) =>
                                                                                setRenameValue(
                                                                                    e.target.value,
                                                                                )
                                                                            }
                                                                            onBlur={
                                                                                commitProjectRename
                                                                            }
                                                                            onKeyDown={(e) => {
                                                                                if (
                                                                                    e.key ===
                                                                                    'Enter'
                                                                                )
                                                                                    commitProjectRename()
                                                                                if (
                                                                                    e.key ===
                                                                                    'Escape'
                                                                                )
                                                                                    setRenamingProjectId(
                                                                                        null,
                                                                                    )
                                                                            }}
                                                                            autoFocus
                                                                        />
                                                                    ) : (
                                                                        <Base.SidebarMenuSubButton
                                                                            isActive={
                                                                                currentProjectId ===
                                                                                project.id
                                                                            }
                                                                            className="flex-1"
                                                                            onClick={() =>
                                                                                navigate({
                                                                                    to: '/project/$projectId',
                                                                                    params: {
                                                                                        projectId:
                                                                                            String(
                                                                                                project.id,
                                                                                            ),
                                                                                    },
                                                                                })
                                                                            }
                                                                        >
                                                                            <File className="h-3.5 w-3.5 shrink-0" />
                                                                            <span className="truncate">
                                                                                {project.name}
                                                                            </span>
                                                                        </Base.SidebarMenuSubButton>
                                                                    )}

                                                                    <DropdownMenu>
                                                                        <DropdownMenuTrigger
                                                                            render={
                                                                                <Button
                                                                                    variant="ghost"
                                                                                    size="icon"
                                                                                    className="h-6 w-6 shrink-0 opacity-0 group-hover/project:opacity-100"
                                                                                />
                                                                            }
                                                                        >
                                                                            <MoreHorizontal className="h-3.5 w-3.5" />
                                                                        </DropdownMenuTrigger>
                                                                        <DropdownMenuContent align="start">
                                                                            <DropdownMenuItem
                                                                                onClick={() => {
                                                                                    setRenamingProjectId(
                                                                                        project.id,
                                                                                    )
                                                                                    setRenameValue(
                                                                                        project.name,
                                                                                    )
                                                                                }}
                                                                            >
                                                                                이름 변경
                                                                            </DropdownMenuItem>
                                                                            <DropdownMenuItem
                                                                                onClick={() =>
                                                                                    duplicateProject.mutate(
                                                                                        project.id,
                                                                                    )
                                                                                }
                                                                            >
                                                                                복제
                                                                            </DropdownMenuItem>
                                                                            <DropdownMenuSeparator />
                                                                            <DropdownMenuItem
                                                                                className="text-destructive focus:text-destructive"
                                                                                onClick={() => {
                                                                                    setTargetProject(
                                                                                        project,
                                                                                    )
                                                                                    setDeleteTarget(
                                                                                        {
                                                                                            type: 'project',
                                                                                            name: project.name,
                                                                                        },
                                                                                    )
                                                                                    setDeleteOpen(
                                                                                        true,
                                                                                    )
                                                                                }}
                                                                            >
                                                                                삭제
                                                                            </DropdownMenuItem>
                                                                        </DropdownMenuContent>
                                                                    </DropdownMenu>
                                                                </div>
                                                            </Base.SidebarMenuSubItem>
                                                        ))
                                                    )}
                                                </Base.SidebarMenuSub>
                                            </CollapsibleContent>
                                        </Collapsible>
                                    </Base.SidebarMenuItem>
                                ))
                            )}
                        </Base.SidebarMenu>
                    </Base.SidebarGroupContent>
                </Base.SidebarGroup>
            </Base.SidebarContent>

            <CreateGroupDialog
                open={createGroupOpen}
                onOpenChange={setCreateGroupOpen}
                onCreate={(name) => createGroup.mutate(name)}
            />
            <CreateProjectDialog
                open={createProjectOpen}
                onOpenChange={setCreateProjectOpen}
                groupName={targetGroup?.name}
                onCreate={(name) =>
                    targetGroup && createProject.mutate({ groupId: targetGroup.id, name })
                }
            />
            <ConfirmDeleteDialog
                open={deleteOpen}
                onOpenChange={setDeleteOpen}
                title={deleteTarget?.type === 'group' ? '그룹 삭제' : '프로젝트 삭제'}
                description={`"${deleteTarget?.name}" ${deleteTarget?.type === 'group' ? '그룹과 포함된 모든 프로젝트를 삭제합니다.' : '프로젝트와 모든 씬, 이미지를 삭제합니다.'} 이 작업은 되돌릴 수 없습니다.`}
                onConfirm={() => {
                    if (deleteTarget?.type === 'group' && targetGroup)
                        handleDeleteGroup(targetGroup)
                    else if (deleteTarget?.type === 'project' && targetProject)
                        handleDeleteProject(targetProject)
                }}
            />
        </>
    )
}
