// web/src/lib/components/app/dialogs/confirm-delete-dialog.svelte
<script lang="ts">
    import * as AlertDialog from '$lib/components/ui/alert-dialog'

    let {
        open = $bindable(false),
        title = '정말 삭제할까요?',
        description = '이 작업은 되돌릴 수 없습니다.',
        onconfirm,
    }: {
        open?: boolean
        title?: string
        description?: string
        onconfirm: () => void
    } = $props()

    function handleConfirm() {
        onconfirm()
        open = false
    }
</script>

<AlertDialog.Root bind:open>
    <AlertDialog.Content>
        <AlertDialog.Header>
            <AlertDialog.Title>{title}</AlertDialog.Title>
            <AlertDialog.Description>{description}</AlertDialog.Description>
        </AlertDialog.Header>
        <AlertDialog.Footer>
            <AlertDialog.Cancel>취소</AlertDialog.Cancel>
            <AlertDialog.Action onclick={handleConfirm}>삭제</AlertDialog.Action>
        </AlertDialog.Footer>
    </AlertDialog.Content>
</AlertDialog.Root>

// web-next/src/components/app/dialogs/confirm-delete-dialog.tsx
import {
    AlertDialog,
    AlertDialogAction,
    AlertDialogCancel,
    AlertDialogContent,
    AlertDialogDescription,
    AlertDialogFooter,
    AlertDialogHeader,
    AlertDialogTitle,
} from '@/components/ui/alert-dialog'

interface ConfirmDeleteDialogProps {
    open: boolean
    onOpenChange: (open: boolean) => void
    title: string
    description: string
    onConfirm: () => void
}

export function ConfirmDeleteDialog({
    open,
    title,
    description,
    onOpenChange,
    onConfirm,
}: ConfirmDeleteDialogProps) {
    return (
        <AlertDialog open={open} onOpenChange={onOpenChange}>
            <AlertDialogContent>
                <AlertDialogHeader>
                    <AlertDialogTitle>{title}</AlertDialogTitle>
                    <AlertDialogDescription>{description}</AlertDialogDescription>
                </AlertDialogHeader>
                <AlertDialogFooter>
                    <AlertDialogCancel>취소</AlertDialogCancel>
                    <AlertDialogAction
                        className="bg-destructive text-destructive-foreground hover:bg-destructive/90"
                        onClick={onConfirm}
                    >
                        삭제
                    </AlertDialogAction>
                </AlertDialogFooter>
            </AlertDialogContent>
        </AlertDialog>
    )
}
