// web-next/src/lib/components/app/project/scene-card.svelte
<script lang="ts">
import { createMutation, useQueryClient } from '@tanstack/svelte-query'
import { Check, Copy, Image, ListPlus, Pencil, Spinner, Trash } from 'phosphor-svelte'
import { onDestroy } from 'svelte'
import { goto } from '$app/navigation'
import { api, imageUrl } from '$lib/api'
import ConfirmDeleteDialog from '$lib/components/app/dialogs/confirm-delete-dialog.svelte'
import { Button } from '$lib/components/ui/button'
import * as ContextMenu from '$lib/components/ui/context-menu'
import { qk } from '$lib/query-keys'
import type { Scene } from '$lib/types'
import { cn } from '$lib/utils'

interface Props {
    scene: Scene
    selected?: boolean
    selectMode?: boolean
    isProcessing?: boolean
    slideshowCount?: number
    onToggleSelect?: (id: number) => void
}

let {
    scene,
    selected = false,
    selectMode = false,
    isProcessing = false,
    slideshowCount = 4,
    onToggleSelect,
}: Props = $props()

const queryClient = useQueryClient()
let currentThumbIndex = $state(0)
let deleteOpen = $state(false)
let interval: ReturnType<typeof setInterval> | null = null

const queueCount = $derived(scene.queueCount ?? 0)
const inQueue = $derived(queueCount > 0)
const images = $derived(scene.latestImages ?? [])
const cycleImages = $derived(slideshowCount > 0 ? images.slice(-slideshowCount) : images)
const currentThumbImg = $derived(cycleImages[currentThumbIndex] ?? null)

$effect(() => {
    if (interval) clearInterval(interval)
    currentThumbIndex = 0
    if (cycleImages.length <= 1) return
    interval = setInterval(() => {
        currentThumbIndex = (currentThumbIndex + 1) % cycleImages.length
    }, 2000)
})

onDestroy(() => {
    if (interval) clearInterval(interval)
})

const deleteScene = createMutation(() => ({
    mutationFn: () => api.scenes({ id: scene.id }).delete(),
    onSuccess: () =>
        queryClient.invalidateQueries({
            queryKey: qk.scenes(scene.projectId),
        }),
}))
const duplicateScene = createMutation(() => ({
    mutationFn: () => api.scenes({ id: scene.id }).duplicate.post(),
    onSuccess: () =>
        queryClient.invalidateQueries({
            queryKey: qk.scenes(scene.projectId),
        }),
}))
const enqueue = createMutation(() => ({
    mutationFn: () => api.queue.enqueue.post({ sceneId: scene.id }),
    onSuccess: () => {
        queryClient.invalidateQueries({ queryKey: [qk.queueStatus()] })
        queryClient.invalidateQueries({
            queryKey: qk.scenes(scene.projectId),
        })
    },
}))
const clearQueue = createMutation(() => ({
    mutationFn: () => api.queue.delete({ query: { sceneId: scene.id } }),
    onSuccess: () => {
        queryClient.invalidateQueries({ queryKey: qk.queueStatus() })
        queryClient.invalidateQueries({
            queryKey: qk.scenes(scene.projectId),
        })
    },
}))
</script>

<ContextMenu.Root>
	<ContextMenu.Trigger>
		<div
			class={cn(
				"relative flex w-56 flex-col overflow-hidden rounded-lg border bg-card transition-all hover:shadow-md",
				inQueue &&
					"border-primary shadow-[0_0_0_1px_color-mix(in_oklch,var(--primary)_30%,transparent)]",
				selected && "ring-2 ring-primary ring-offset-2",
			)}
		>
			{#if inQueue}
				<div
					class="absolute top-1.5 right-1.5 z-20 rounded bg-primary px-1.5 py-0.5 text-[10px] leading-none font-semibold text-primary-foreground shadow"
				>
					큐 {queueCount}
				</div>
			{/if}

			{#if selectMode && onToggleSelect}
				<button
					type="button"
					class={cn(
						"absolute top-1.5 left-1.5 z-20 flex h-5 w-5 items-center justify-center rounded border-2 transition-colors",
						selected
							? "border-primary bg-primary text-primary-foreground"
							: "border-white/70 bg-black/30 text-transparent hover:border-primary",
					)}
					onclick={(event) => {
						event.stopPropagation();
						onToggleSelect?.(scene.id);
					}}
				>
					<Check class="h-3 w-3" />
				</button>
			{/if}

			<button
				type="button"
				class="group relative aspect-[3/4] w-full overflow-hidden bg-muted text-left"
				onclick={() => goto(`/scene/${scene.id}/images`)}
			>
				{#if currentThumbImg === null}
					<div class="flex h-full items-center justify-center">
						<Image class="h-10 w-10 text-muted-foreground/20" />
					</div>
				{:else}
					<img
						src={imageUrl(
							currentThumbImg.thumbnailPath ??
								currentThumbImg.filePath,
						)}
						alt={scene.name}
						class="h-full w-full object-cover transition-transform duration-200 group-hover:scale-105"
						loading="lazy"
					/>
				{/if}

				<div
					class="absolute right-0 bottom-0 left-0 flex items-end justify-between gap-1 bg-gradient-to-t from-black/65 to-transparent px-1.5 pt-8 pb-1.5"
				>
					<span
						class="min-w-0 truncate text-[10px] font-medium text-white/90"
						>{scene.name}</span
					>
					{#if cycleImages.length > 1}
						<div class="flex shrink-0 gap-1">
							{#each cycleImages as _, index}
								<div
									class={cn(
										"h-1 w-1 rounded-full transition-colors",
										index === currentThumbIndex
											? "bg-white"
											: "bg-white/35",
									)}
								></div>
							{/each}
						</div>
					{/if}
					<span
						class="shrink-0 text-[10px] font-medium text-white/90"
					>
						{(scene.imageCount ?? 0) > 0
							? `${scene.imageCount}장`
							: ""}
					</span>
				</div>

				{#if isProcessing}
					<div
						class="absolute inset-0 flex items-center justify-center bg-primary/20 backdrop-blur-[2px]"
					>
						<div class="flex flex-col items-center gap-1.5">
							<Spinner
								class="h-7 w-7 animate-spin text-white drop-shadow"
							/>
							<span
								class="text-[10px] font-semibold text-white drop-shadow"
								>생성 중</span
							>
						</div>
					</div>
				{/if}
			</button>

			<div class="flex border-t">
				<Button
					variant="ghost"
					size="sm"
					class="h-8 flex-1 gap-1 rounded-none text-xs"
					onclick={() => enqueue.mutate()}
					disabled={enqueue.isPending}
				>
					<ListPlus class="h-3.5 w-3.5" />큐 추가
				</Button>
				<div class="w-px bg-border"></div>
				<Button
					variant="ghost"
					size="sm"
					class="h-8 flex-1 gap-1 rounded-none text-xs text-muted-foreground hover:text-destructive"
					onclick={() => clearQueue.mutate()}
					disabled={clearQueue.isPending || !inQueue}
				>
					<Trash class="h-3.5 w-3.5" />큐 삭제
				</Button>
				<div class="w-px bg-border"></div>
				<Button
					variant="ghost"
					size="sm"
					class="h-8 flex-1 gap-1 rounded-none text-xs"
					onclick={() => goto(`/scene/${scene.id}`)}
				>
					<Pencil class="h-3.5 w-3.5" />
					수정
				</Button>
			</div>
		</div>
	</ContextMenu.Trigger>
	<ContextMenu.Content>
		<ContextMenu.Item
			onclick={() => duplicateScene.mutate()}
			disabled={duplicateScene.isPending}
		>
			<Copy class="mr-2 h-4 w-4" />
			복제
		</ContextMenu.Item>
		<ContextMenu.Separator />
		<ContextMenu.Item
			class="text-destructive focus:text-destructive"
			onclick={() => (deleteOpen = true)}
		>
			<Trash class="mr-2 h-4 w-4" />
			삭제
		</ContextMenu.Item>
	</ContextMenu.Content>
</ContextMenu.Root>

<ConfirmDeleteDialog
	bind:open={deleteOpen}
	title="씬 삭제"
	description={`"${scene.name}" 씬과 모든 생성된 이미지를 삭제합니다. 되돌릴 수 없습니다.`}
	onConfirm={() => deleteScene.mutate()}
/>

// web/src/features/project/scene-card.tsx
import type { EnqueuePosition, ProjectSettings, SceneSummary } from '@nai-factory/shared'
import { useNavigate } from '@tanstack/react-router'
import { Check, Copy, Image, ListPlus, Loader, MoreHorizontal, Pencil, Trash2 } from 'lucide-react'
import { useEffect, useState } from 'react'

import { ConfirmDeleteDialog } from '@/components/confirm-delete-dialog'
import { Button } from '@/components/ui/button'
import {
    ContextMenu,
    ContextMenuContent,
    ContextMenuItem,
    ContextMenuSeparator,
    ContextMenuTrigger,
} from '@/components/ui/context-menu'
import {
    DropdownMenu,
    DropdownMenuContent,
    DropdownMenuItem,
    DropdownMenuSeparator,
    DropdownMenuTrigger,
} from '@/components/ui/dropdown-menu'
import { ImageProgressBar } from '@/features/queue/generation-progress'
import { formatSeconds } from '@/features/queue/generation-timing'
import { useGenerationStatus } from '@/features/queue/use-queue'
import { assetUrl } from '@/lib/api'
import { cn } from '@/lib/utils'

import { useSceneMutations } from './use-scene-mutations'

interface SceneCardProps {
    scene: SceneSummary
    index: number
    selected?: boolean
    selectMode?: boolean
    isProcessing?: boolean
    slideshowCount?: number
    cardSize?: ProjectSettings['sceneCardSize']
    onToggleSelect?: (id: number) => void
    onSelectDragStart?: (index: number, selected: boolean) => void
}

const SCENE_CARD_SIZE_CLASSES: Record<ProjectSettings['sceneCardSize'], string> = {
    sm: 'w-44',
    md: 'w-56',
    lg: 'w-72',
}

const SCENE_CARD_EMPTY_ICON_CLASSES: Record<ProjectSettings['sceneCardSize'], string> = {
    sm: 'h-8 w-8',
    md: 'h-10 w-10',
    lg: 'h-12 w-12',
}

export function SceneCard({
    scene,
    index,
    selected = false,
    selectMode = false,
    isProcessing = false,
    slideshowCount = 4,
    cardSize = 'md',
    onToggleSelect,
    onSelectDragStart,
}: SceneCardProps) {
    const navigate = useNavigate()

    const queueCount = scene.queueCount ?? 0
    const inQueue = queueCount > 0
    const images = scene.latestImages ?? []
    const cycleImages = images.slice(0, slideshowCount)

    const [slideshowTick, setSlideshowTick] = useState(0)
    const [deleteOpen, setDeleteOpen] = useState(false)
    const currentThumbIndex = cycleImages.length > 1 ? slideshowTick % cycleImages.length : 0

    useEffect(() => {
        if (cycleImages.length <= 1) return
        const interval = setInterval(() => setSlideshowTick((tick) => tick + 1), 2000)
        return () => clearInterval(interval)
    }, [cycleImages.length])

    const currentThumbImg = cycleImages[currentThumbIndex] ?? null

    const { remove, duplicate, enqueue, clearQueue } = useSceneMutations(scene.projectId)
    const enqueueScene = (position: EnqueuePosition) =>
        enqueue.mutate({ sceneIds: [scene.id], position })

    return (
        <>
            <ContextMenu>
                <ContextMenuTrigger
                    render={
                        <div
                            className={cn(
                                'group/scene-card relative flex flex-col overflow-hidden rounded-lg border bg-card transition-all hover:shadow-md',
                                SCENE_CARD_SIZE_CLASSES[cardSize],
                                inQueue &&
                                    'border-primary shadow-[0_0_0_1px_color-mix(in_oklch,var(--primary)_30%,transparent)]',
                                selected && 'ring-2 ring-primary ring-offset-2',
                            )}
                        />
                    }
                >
                    <DropdownMenu>
                        <DropdownMenuTrigger
                            render={
                                <Button
                                    variant="ghost"
                                    size="icon-xs"
                                    aria-label={`${scene.name} 메뉴 열기`}
                                    className="pointer-events-none absolute top-1.5 right-1.5 z-30 rounded bg-black/35 text-white opacity-0 shadow-sm hover:bg-black/55 hover:text-white group-hover/scene-card:pointer-events-auto group-hover/scene-card:opacity-100 aria-expanded:pointer-events-auto aria-expanded:opacity-100 [@media(hover:none)]:pointer-events-auto [@media(hover:none)]:opacity-100"
                                    onPointerDown={(e) => e.stopPropagation()}
                                />
                            }
                        >
                            <MoreHorizontal className="h-3.5 w-3.5" />
                        </DropdownMenuTrigger>
                        <DropdownMenuContent align="end" sideOffset={6}>
                            <DropdownMenuItem
                                onClick={() => enqueueScene('front')}
                                disabled={enqueue.isPending}
                            >
                                <ListPlus className="mr-2 h-4 w-4" />큐 맨 앞 추가
                            </DropdownMenuItem>
                            <DropdownMenuSeparator />
                            <DropdownMenuItem
                                onClick={() => duplicate.mutate(scene)}
                                disabled={duplicate.isPending}
                            >
                                <Copy className="mr-2 h-4 w-4" />
                                복제
                            </DropdownMenuItem>
                            <DropdownMenuSeparator />
                            <DropdownMenuItem
                                className="text-destructive focus:text-destructive"
                                onClick={() => setDeleteOpen(true)}
                            >
                                <Trash2 className="mr-2 h-4 w-4" />
                                삭제
                            </DropdownMenuItem>
                        </DropdownMenuContent>
                    </DropdownMenu>

                    {onToggleSelect && (
                        <button
                            type="button"
                            aria-label={selected ? `${scene.name} 선택 해제` : `${scene.name} 선택`}
                            className={cn(
                                'pointer-events-none absolute top-1.5 left-1.5 z-20 flex h-6 w-6 items-center justify-center rounded border-2 opacity-0 after:absolute after:-inset-2 shadow-sm transition-all group-hover/scene-card:pointer-events-auto group-hover/scene-card:opacity-100 focus-visible:pointer-events-auto focus-visible:opacity-100 [@media(hover:none)]:pointer-events-auto [@media(hover:none)]:opacity-100',
                                selected
                                    ? 'border-primary bg-primary text-primary-foreground'
                                    : 'border-white/75 bg-black/35 text-transparent hover:border-primary hover:bg-primary hover:text-primary-foreground',
                            )}
                            onClick={(e) => {
                                e.stopPropagation()
                                if (onSelectDragStart && e.detail > 0) return
                                onToggleSelect(scene.id)
                            }}
                            onPointerDown={(e) => {
                                if (!onSelectDragStart || e.button !== 0) return
                                e.preventDefault()
                                e.stopPropagation()
                                onSelectDragStart(index, selected)
                            }}
                        >
                            <Check className="h-3 w-3" />
                        </button>
                    )}

                    <button
                        type="button"
                        className="group/thumb relative aspect-[3/4] w-full overflow-hidden bg-muted text-left"
                        onClick={() => {
                            if (selectMode && onToggleSelect) {
                                onToggleSelect(scene.id)
                                return
                            }

                            void navigate({
                                to: '/scene/$sceneId/images',
                                params: { sceneId: String(scene.id) },
                            })
                        }}
                    >
                        {currentThumbImg === null ? (
                            <div className="flex h-full items-center justify-center">
                                <Image
                                    className={cn(
                                        'text-muted-foreground/20',
                                        SCENE_CARD_EMPTY_ICON_CLASSES[cardSize],
                                    )}
                                />
                            </div>
                        ) : (
                            <img
                                key={currentThumbIndex}
                                src={assetUrl(currentThumbImg.thumbAssetId)}
                                alt={scene.name}
                                className="h-full w-full object-cover transition-transform duration-200 group-hover/thumb:scale-105"
                                loading="lazy"
                            />
                        )}

                        <div className="absolute right-0 bottom-0 left-0 flex items-end justify-between gap-1 bg-gradient-to-t from-black/65 to-transparent px-1.5 pt-8 pb-1.5">
                            <div className="flex min-w-0 flex-1 flex-col items-start gap-1">
                                {(inQueue || isProcessing) && (
                                    <div className="flex flex-wrap items-center gap-1">
                                        {isProcessing && <SceneCardGeneratingBadge />}
                                        {inQueue && (
                                            <span className="rounded bg-primary px-1.5 py-0.5 text-[10px] leading-none font-semibold text-primary-foreground shadow">
                                                큐 {queueCount}
                                            </span>
                                        )}
                                    </div>
                                )}
                                <span className="max-w-full truncate text-[10px] font-medium text-white/90">
                                    {scene.name}
                                </span>
                            </div>

                            {cycleImages.length > 1 && (
                                <div className="flex shrink-0 gap-1">
                                    {cycleImages.map((_, i) => (
                                        <div
                                            // Index keys: the dots are positional.
                                            key={i}
                                            className={cn(
                                                'h-1 w-1 rounded-full transition-colors',
                                                i === currentThumbIndex
                                                    ? 'bg-white'
                                                    : 'bg-white/35',
                                            )}
                                        />
                                    ))}
                                </div>
                            )}

                            <span className="shrink-0 text-[10px] font-medium text-white/90">
                                {(scene.imageCount ?? 0) > 0 ? `${scene.imageCount}장` : ''}
                            </span>
                        </div>

                        {/* Keep the image visible while generating; progress runs along the bottom edge. */}
                        {isProcessing && <SceneCardGenerationBar />}
                    </button>

                    <div className="flex border-t">
                        <Button
                            variant="ghost"
                            size="sm"
                            className="min-w-0 flex-1 shrink basis-0 gap-1 rounded-none px-1 text-xs"
                            aria-label="큐 추가"
                            onPointerDown={(e) => e.stopPropagation()}
                            onClick={() => enqueueScene('back')}
                            disabled={enqueue.isPending}
                        >
                            <ListPlus className="h-3.5 w-3.5" />
                            <span className={cn('truncate', cardSize === 'sm' && 'sr-only')}>
                                큐 추가
                            </span>
                        </Button>
                        <div className="w-px bg-border" />
                        <Button
                            variant="ghost"
                            size="sm"
                            className="min-w-0 flex-1 shrink basis-0 gap-1 rounded-none px-1 text-xs text-muted-foreground hover:text-destructive"
                            aria-label="큐 삭제"
                            onPointerDown={(e) => e.stopPropagation()}
                            onClick={() => clearQueue.mutate([scene])}
                            disabled={clearQueue.isPending || !inQueue}
                        >
                            <Trash2 className="h-3.5 w-3.5" />
                            <span className={cn('truncate', cardSize === 'sm' && 'sr-only')}>
                                큐 삭제
                            </span>
                        </Button>
                        <div className="w-px bg-border" />
                        <Button
                            variant="ghost"
                            size="sm"
                            className="min-w-0 flex-1 shrink basis-0 gap-1 rounded-none px-1 text-xs"
                            aria-label="수정"
                            onPointerDown={(e) => e.stopPropagation()}
                            onClick={() =>
                                navigate({
                                    to: '/scene/$sceneId',
                                    params: { sceneId: String(scene.id) },
                                })
                            }
                        >
                            <Pencil className="h-3.5 w-3.5" />
                            <span className={cn('truncate', cardSize === 'sm' && 'sr-only')}>
                                수정
                            </span>
                        </Button>
                    </div>
                </ContextMenuTrigger>

                <ContextMenuContent>
                    <ContextMenuItem
                        onClick={() => enqueueScene('front')}
                        disabled={enqueue.isPending}
                    >
                        <ListPlus className="mr-2 h-4 w-4" />큐 맨 앞 추가
                    </ContextMenuItem>
                    <ContextMenuSeparator />
                    <ContextMenuItem
                        onClick={() => duplicate.mutate(scene)}
                        disabled={duplicate.isPending}
                    >
                        <Copy className="mr-2 h-4 w-4" />
                        복제
                    </ContextMenuItem>
                    <ContextMenuSeparator />
                    <ContextMenuItem
                        className="text-destructive focus:text-destructive"
                        onClick={() => setDeleteOpen(true)}
                    >
                        <Trash2 className="mr-2 h-4 w-4" />
                        삭제
                    </ContextMenuItem>
                </ContextMenuContent>
            </ContextMenu>

            <ConfirmDeleteDialog
                open={deleteOpen}
                onOpenChange={setDeleteOpen}
                title="씬 삭제"
                description={`"${scene.name}" 씬과 모든 생성된 이미지를 삭제합니다. 되돌릴 수 없습니다.`}
                onConfirm={() => remove.mutate([scene.id])}
            />
        </>
    )
}

/** Rendered only on the card being generated, so just that card ticks with the clock. */
function SceneCardGeneratingBadge() {
    const { progress } = useGenerationStatus()

    return (
        <span className="flex items-center gap-1 rounded bg-background/90 px-1.5 py-0.5 text-[10px] leading-none font-semibold text-foreground tabular-nums shadow">
            <Loader className="h-2.5 w-2.5 animate-spin motion-reduce:animate-none" />
            생성 중{progress ? ` · ${formatSeconds(progress.elapsedMs / 1000)}` : ''}
        </span>
    )
}

function SceneCardGenerationBar() {
    const { progress } = useGenerationStatus()

    return (
        <ImageProgressBar
            progress={progress}
            className="pointer-events-none absolute inset-x-0 bottom-0 h-1 bg-black/30"
        />
    )
}
