// web-next/src/routes/scene/$sceneId/images/index.tsx
import {
    closestCenter,
    DndContext,
    type DragEndEvent,
    PointerSensor,
    useSensor,
    useSensors,
} from '@dnd-kit/core'
import { arrayMove, rectSortingStrategy, SortableContext } from '@dnd-kit/sortable'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { createFileRoute, Outlet, useNavigate } from '@tanstack/react-router'
import { ArrowLeft } from 'lucide-react'
import { useEffect, useState } from 'react'
import { ConfirmDeleteDialog } from '@/components/app/dialogs/confirm-delete-dialog'
import { SortableImageItem } from '@/components/app/project/sortable-image-item'
import { Button } from '@/components/ui/button'
import { api, imageUrl } from '@/lib/api'
import { qk } from '@/lib/queries'

type Image = {
    id: number
    filePath: string
    thumbnailPath?: string | null
}

export const Route = createFileRoute('/scene/$sceneId/images/')({ component: ImagesPage })

function ImagesPage() {
    const { sceneId } = Route.useParams()
    const navigate = useNavigate()
    const queryClient = useQueryClient()
    const scenId = Number(sceneId)

    const imagesQuery = useQuery({
        queryKey: qk.images(scenId),
        queryFn: async () => {
            const { data } = await api.images.get({ query: { sceneId: scenId } })
            return (data ?? []) as Image[]
        },
    })

    const [items, setItems] = useState<Image[]>([])
    const [deleteTarget, setDeleteTarget] = useState<Image | null>(null)

    // Sync DnD items from server data
    useEffect(() => {
        if (imagesQuery.data) setItems(imagesQuery.data)
    }, [imagesQuery.data])

    const sensors = useSensors(useSensor(PointerSensor, { activationConstraint: { distance: 8 } }))

    const deleteImage = useMutation({
        mutationFn: (img: Image) => api.images({ id: img.id }).delete(),
        onSuccess: () => {
            queryClient.invalidateQueries({ queryKey: qk.images(scenId) })
            setDeleteTarget(null)
        },
    })

    const reorderImages = useMutation({
        mutationFn: ({
            id,
            prevId,
            nextId,
        }: {
            id: number
            prevId: number | null
            nextId: number | null
        }) => api.images({ id }).order.patch({ prevId, nextId }),
        onSuccess: () => queryClient.invalidateQueries({ queryKey: qk.images(scenId) }),
    })

    function handleDragEnd(event: DragEndEvent) {
        const { active, over } = event
        if (!over || active.id === over.id) return

        const oldIndex = items.findIndex((i) => i.id === active.id)
        const newIndex = items.findIndex((i) => i.id === over.id)
        const newItems = arrayMove(items, oldIndex, newIndex)
        setItems(newItems)

        const prevId = newIndex > 0 ? newItems[newIndex - 1].id : null
        const nextId = newIndex < newItems.length - 1 ? newItems[newIndex + 1].id : null
        reorderImages.mutate({ id: active.id as number, prevId, nextId })
    }

    return (
        <>
            <div className="flex h-full flex-col gap-4">
                {/* Header */}
                <div className="flex items-center gap-2">
                    <Button
                        variant="ghost"
                        size="icon"
                        className="h-8 w-8 shrink-0"
                        onClick={() => navigate({ to: '/scene/$sceneId', params: { sceneId } })}
                    >
                        <ArrowLeft className="h-4 w-4" />
                    </Button>
                    <span className="text-sm font-medium">
                        이미지 ({imagesQuery.data?.length ?? 0}장)
                    </span>
                </div>

                {/* Image grid */}
                {imagesQuery.isPending ? (
                    <div className="flex flex-1 items-center justify-center text-sm text-muted-foreground">
                        불러오는 중...
                    </div>
                ) : items.length === 0 ? (
                    <div className="flex flex-1 items-center justify-center text-sm text-muted-foreground">
                        생성된 이미지가 없습니다.
                    </div>
                ) : (
                    <DndContext
                        sensors={sensors}
                        collisionDetection={closestCenter}
                        onDragEnd={handleDragEnd}
                    >
                        <SortableContext
                            items={items.map((i) => i.id)}
                            strategy={rectSortingStrategy}
                        >
                            <div className="grid grid-cols-[repeat(auto-fill,minmax(160px,1fr))] gap-3 pb-4">
                                {items.map((img) => (
                                    <SortableImageItem
                                        key={img.id}
                                        img={img}
                                        imageUrl={imageUrl(img.thumbnailPath ?? img.filePath)}
                                        onView={(img) =>
                                            navigate({
                                                to: '/scene/$sceneId/images/$imageId',
                                                params: { sceneId, imageId: String(img.id) },
                                            })
                                        }
                                        onDelete={(img) => setDeleteTarget(img)}
                                    />
                                ))}
                            </div>
                        </SortableContext>
                    </DndContext>
                )}
            </div>

            {/* Image viewer overlay */}
            <Outlet />

            {/* Delete dialog */}
            <ConfirmDeleteDialog
                open={deleteTarget !== null}
                onOpenChange={(open) => !open && setDeleteTarget(null)}
                title="이미지 삭제"
                description="이 이미지를 삭제합니다. 되돌릴 수 없습니다."
                onConfirm={() => deleteTarget && deleteImage.mutate(deleteTarget)}
            />
        </>
    )
}

// web/src/routes/project/[id]/images/+page.svelte
<script lang="ts">
    import { page } from '$app/state'
    import { goto } from '$app/navigation'
    import { createQuery, createMutation, useQueryClient } from '@tanstack/svelte-query'
    import { api } from '$lib/api'
    import { qk } from '$lib/queries'
    import { DragDropProvider } from '@dnd-kit/svelte'
    import { move } from '@dnd-kit/helpers'
    import SortableImageItem from '$lib/components/app/project/sortable-image-item.svelte'
    import ConfirmDeleteDialog from '$lib/components/app/dialogs/confirm-delete-dialog.svelte'
    import { Button } from '$lib/components/ui/button'
    import ArrowLeftIcon from '@lucide/svelte/icons/arrow-left'

    type Image = NonNullable<Awaited<ReturnType<typeof api.api.images.get>>['data']>[number]

    const BASE_URL = import.meta.env.VITE_API_URL ?? 'http://localhost:3000'

    const projectId = $derived(page.params.id)
    const sceneId = $derived(+(page.url.searchParams.get('scene') ?? '0'))

    const queryClient = useQueryClient()

    const scenesQuery = createQuery(() => ({
        queryKey: qk.scenes(+projectId),
        queryFn: async () => {
            const { data } = await api.api.scenes.get({ query: { projectId: +projectId } })
            return data ?? []
        },
        enabled: !!projectId,
    }))
    const scene = $derived(scenesQuery.data?.find((s) => s.id === sceneId) ?? null)

    const imagesQuery = createQuery(() => ({
        queryKey: qk.images(sceneId),
        queryFn: async () => {
            const { data } = await api.api.images.get({ query: { sceneId } })
            return data ?? []
        },
        enabled: sceneId > 0,
    }))

    const deleteImage = createMutation(() => ({
        mutationFn: (id: number) => api.api.images({ id }).delete(),
        onSuccess: () => queryClient.invalidateQueries({ queryKey: qk.images(sceneId) }),
    }))

    let deleteOpen = $state(false)
    let imageToDelete = $state<Image | null>(null)

    let localImages = $state<Image[]>([])
    let isDragging = $state(false)

    $effect(() => {
        if (!isDragging) localImages = [...(imagesQuery.data ?? [])]
    })

    function getImageUrl(path: string) {
        return `${BASE_URL}/${path}`
    }

    function openViewer(img: Image) {
        goto(`/project/${projectId}/images/${img.id}?scene=${sceneId}`)
    }

    function onDragStart() { isDragging = true }
    function onDragOver(event: any) { localImages = move(localImages, event) }

    async function onDragEnd(event: any) {
        isDragging = false
        if (event.canceled) return

        const sourceId = event.operation.source?.id as number
        const newIndex = localImages.findIndex((i) => i.id === sourceId)
        const prevId = localImages[newIndex - 1]?.id ?? null
        const nextId = localImages[newIndex + 1]?.id ?? null

        await api.api.images({ id: sourceId }).order.patch({ prevId, nextId })
        queryClient.invalidateQueries({ queryKey: qk.images(sceneId) })
    }
</script>

<div class="flex h-dvh flex-col">
    <!-- Header -->
    <div class="flex shrink-0 items-center gap-3 border-b px-6 py-4">
        <Button variant="ghost" size="icon-sm" onclick={() => history.back()}>
            <ArrowLeftIcon class="h-4 w-4" />
        </Button>
        <div>
            <h1 class="text-base font-semibold">{scene?.name ?? '로딩 중...'}</h1>
            <p class="text-xs text-muted-foreground">
                이미지 {localImages.length}장 · 드래그로 순서 변경 · 클릭하면 전체 화면으로 보기
            </p>
        </div>
    </div>

    <!-- Grid -->
    <div class="flex-1 overflow-auto p-6">
        {#if imagesQuery.isPending}
            <div class="grid grid-cols-2 gap-4 sm:grid-cols-3 lg:grid-cols-4 xl:grid-cols-5">
                {#each Array.from({ length: 6 }) as _}
                    <div class="aspect-[3/4] animate-pulse rounded-lg bg-muted"></div>
                {/each}
            </div>
        {:else if localImages.length === 0}
            <div class="flex h-full items-center justify-center text-muted-foreground">
                <p class="text-sm">아직 생성된 이미지가 없습니다</p>
            </div>
        {:else}
            <DragDropProvider {onDragStart} {onDragOver} {onDragEnd}>
                <div class="grid grid-cols-2 gap-4 sm:grid-cols-3 lg:grid-cols-4 xl:grid-cols-5">
                    {#each localImages as img, index (img.id)}
                        <SortableImageItem
                            {img}
                            {index}
                            imageUrl={getImageUrl(img.thumbnailPath ?? img.filePath)}
                            onview={openViewer}
                            ondelete={(i) => { imageToDelete = i; deleteOpen = true }}
                        />
                    {/each}
                </div>
            </DragDropProvider>
        {/if}
    </div>
</div>

<ConfirmDeleteDialog
    bind:open={deleteOpen}
    title="이미지 삭제"
    description="이 이미지를 삭제합니다. 이 작업은 되돌릴 수 없습니다."
    onconfirm={() => imageToDelete && deleteImage.mutate(imageToDelete.id)}
/>
